In [1]:
import os, json
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path(os.getcwd()).parent
CONFIG_PATH = PROJECT_ROOT / "src" / "config.json"
with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    cfg = json.load(f)

FEATURES = Path(cfg["FEATURES"])
RESULTS  = Path(cfg["RESULTS"])

print("FEATURES:", FEATURES)
print("RESULTS :", RESULTS)

DATA_PATH = FEATURES / "weekly_category.parquet"
print(f"Reading data from: {DATA_PATH}")

FEATURES: D:\STAT3013.Q12_Group01\features
RESULTS : D:\STAT3013.Q12_Group01\results
Reading data from: D:\STAT3013.Q12_Group01\features\weekly_category.parquet

In [2]:
import pandas as pd
import numpy as np

wd = pd.read_parquet(FEATURES / "weekly_category.parquet")
wd.columns = wd.columns.str.lower()
forecast_df = wd.sort_values(["group_id", "week_no"]).copy()
forecast_df["time_idx"] = forecast_df["week_no"] - forecast_df["week_no"].min()

# Map cột 'target' dùng cho forecast (ở đây dùng 'sales' làm target)
if "target" not in forecast_df.columns:
    if "sales" in forecast_df.columns:
        forecast_df = forecast_df.rename(columns={"sales": "target"})
    elif "sales_value" in forecast_df.columns:
        forecast_df["target"] = forecast_df["sales_value"]
    elif "qty" in forecast_df.columns:
        forecast_df["target"] = forecast_df["qty"]
    else:
        raise ValueError(
            "Không tìm thấy cột 'sales', 'sales_value' hoặc 'qty' để map sang 'target'."
        )

print("forecast_df shape:", forecast_df.shape)
forecast_df.head()

forecast_df shape: (1083, 16)

,week_no,group_id,qty,target,retail_disc,coupon_disc,coupon_match_disc,avg_price,promo_display,promo_mailer,promo_price_red,total_disc,gross_sales,discount_rate,weekofyear,time_idx
0,1,AUTOMOTIVE,1,4.99,0.0,0.0,0.0,4.990,0.0,0.0,0.0,0.0,4.99,0.0,1,0
148,8,AUTOMOTIVE,1,4.45,0.0,0.0,0.0,4.450,0.0,0.0,0.0,0.0,4.45,0.0,8,7
193,10,AUTOMOTIVE,1,17.99,0.0,0.0,0.0,15.230,0.0,0.0,0.0,0.0,17.99,0.0,10,9
216,11,AUTOMOTIVE,1,0.50,0.0,0.0,0.0,0.500,0.0,0.0,0.0,0.0,0.50,0.0,11,10
264,13,AUTOMOTIVE,2,16.49,0.0,0.0,0.0,8.245,0.0,0.0,0.0,0.0,16.49,0.0,13,12

In [3]:
group_target_sum = (
    forecast_df
    .groupby("group_id")["target"]
    .sum()
    .sort_values(ascending=False)
)

# Lấy top 10 group_id
top_groups = group_target_sum.head(10).index.tolist()

print("Top 10 group_id theo tổng 'target':")
print(group_target_sum.head(10))

# Giữ lại dữ liệu của các group này
forecast_df_small = forecast_df[forecast_df["group_id"].isin(top_groups)].copy()

# Danh sách groups dùng cho vòng for ARIMA / TFT
groups = top_groups

len(groups), groups

Top 10 group_id theo tổng 'target':
group_id
GROCERY            1642604.30
DRUG GM             423654.91
MEAT                226239.99
PRODUCE             217569.11
KIOSK-GAS           197788.38
MEAT-PCKGD          168400.29
DELI                103753.60
PASTRY               49537.94
MISC SALES TRAN      41117.99
NUTRITION            35541.83
Name: target, dtype: float64

(10,
 ['GROCERY',
  'DRUG GM',
  'MEAT',
  'PRODUCE',
  'KIOSK-GAS',
  'MEAT-PCKGD',
  'DELI',
  'PASTRY',
  'MISC SALES TRAN',
  'NUTRITION'])

In [4]:
import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning

# Tắt các cảnh báo rối mắt
warnings.filterwarnings("ignore")
warnings.simplefilter('ignore', ConvergenceWarning)

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error

def mape(y_true, y_pred):
    y_true=np.array(y_true); y_pred=np.array(y_pred)
    denom=np.where(y_true==0,1,y_true)
    return np.mean(np.abs((y_true-y_pred)/denom))

HORIZON=2
WINDOWS=5

arima_metrics=[]
for g in groups:
    sub = forecast_df_small[forecast_df_small.group_id==g].sort_values("time_idx")
    y = sub["target"].values
    t = sub["time_idx"].values
    max_t = t.max()
    cutoffs=[max_t-HORIZON-i*HORIZON for i in range(WINDOWS)][::-1]

    for c in cutoffs:
        train_y = y[t<=c]
        test_y  = y[(t>c)&(t<=c+HORIZON)]
        if len(train_y)<10 or len(test_y)<HORIZON: 
            continue
        try:
            fit = ARIMA(train_y, order=(1,1,1)).fit()
            pred = fit.forecast(steps=HORIZON)
        except:
            pred = np.repeat(train_y.mean(), HORIZON)

        arima_metrics.append({
            "group_id": g,
            "rmse": np.sqrt(mean_squared_error(test_y, pred)),
            "mae":  mean_absolute_error(test_y, pred),
            "mape": mape(test_y, pred)
        })

arima_metrics[:3]

[{'group_id': 'GROCERY',
  'rmse': np.float64(5438.531606992048),
  'mae': 5435.013845279569,
  'mape': np.float64(0.1256392492451597)},
 {'group_id': 'GROCERY',
  'rmse': np.float64(3832.2184538992815),
  'mae': 3008.033256530729,
  'mape': np.float64(0.06195609692111692)},
 {'group_id': 'GROCERY',
  'rmse': np.float64(6031.60797581148),
  'mae': 6031.580350660955,
  'mape': np.float64(0.1393374857310393)}]

In [5]:
from prophet import Prophet
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Đảm bảo hàm mape đã được định nghĩa từ trước
# def mape(y_true, y_pred): ...

prophet_metrics = []

for g in groups:
    # Lấy dữ liệu của từng nhóm
    sub = forecast_df_small[forecast_df_small.group_id == g].sort_values("time_idx").copy()

    # Prophet yêu cầu cột 'ds' (datetime) và 'y' (target)
    sub["ds"] = pd.to_datetime(sub["week_no"], unit="W", origin="unix")
    sub["y"]  = sub["target"]

    max_t = sub["time_idx"].max()
    # Tạo các điểm cắt (cutoffs) để test
    cutoffs = [max_t - HORIZON - i * HORIZON for i in range(WINDOWS)][::-1]

    for c in cutoffs:
        train = sub[sub.time_idx <= c][["ds", "y"]]
        test  = sub[(sub.time_idx > c) & (sub.time_idx <= c + HORIZON)]

        if len(train) < 10 or len(test) < HORIZON:
            continue

        # Huấn luyện mô hình
        mp = Prophet()
        mp.fit(train)

        # Dự báo
        future = pd.DataFrame({"ds": pd.to_datetime(test["week_no"], unit="W", origin="unix")})
        fc = mp.predict(future)
        pred = fc["yhat"].values

        # --- ĐOẠN SỬA LỖI QUAN TRỌNG ---
        # Tính MSE trước, sau đó dùng np.sqrt để ra RMSE
        rmse_val = np.sqrt(mean_squared_error(test["target"], pred))
        
        prophet_metrics.append({
            "group_id": g,
            "rmse": rmse_val,
            "mae":  mean_absolute_error(test["target"], pred),
            "mape": mape(test["target"], pred)
        })

# In kết quả
prophet_metrics[:3]

Importing plotly failed. Interactive plots will not work.

14:34:54 - cmdstanpy - INFO - Chain [1] start processing

14:34:54 - cmdstanpy - INFO - Chain [1] done processing

14:34:54 - cmdstanpy - INFO - Chain [1] start processing

14:34:54 - cmdstanpy - INFO - Chain [1] done processing

14:34:54 - cmdstanpy - INFO - Chain [1] start processing

14:34:54 - cmdstanpy - INFO - Chain [1] done processing

14:34:55 - cmdstanpy - INFO - Chain [1] start processing

14:34:55 - cmdstanpy - INFO - Chain [1] done processing

14:34:55 - cmdstanpy - INFO - Chain [1] start processing

14:34:55 - cmdstanpy - INFO - Chain [1] done processing

14:34:55 - cmdstanpy - INFO - Chain [1] start processing

14:34:55 - cmdstanpy - INFO - Chain [1] done processing

14:34:55 - cmdstanpy - INFO - Chain [1] start processing

14:34:55 - cmdstanpy - INFO - Chain [1] done processing

14:34:56 - cmdstanpy - INFO - Chain [1] start processing

14:34:56 - cmdstanpy - INFO - Chain [1] done processing

14:34:56 - cmdstanpy - INFO - Chain [1] start processing

14:34:56 - cmdstanpy - INFO - Chain [1] done processing

14:34:56 - cmdstanpy - INFO - Chain [1] start processing

14:34:56 - cmdstanpy - INFO - Chain [1] done processing

14:34:56 - cmdstanpy - INFO - Chain [1] start processing

14:34:56 - cmdstanpy - INFO - Chain [1] done processing

14:34:57 - cmdstanpy - INFO - Chain [1] start processing

14:34:57 - cmdstanpy - INFO - Chain [1] done processing

14:34:57 - cmdstanpy - INFO - Chain [1] start processing

14:34:57 - cmdstanpy - INFO - Chain [1] done processing

14:34:57 - cmdstanpy - INFO - Chain [1] start processing

14:34:57 - cmdstanpy - INFO - Chain [1] done processing

14:34:57 - cmdstanpy - INFO - Chain [1] start processing

14:34:57 - cmdstanpy - INFO - Chain [1] done processing

14:34:57 - cmdstanpy - INFO - Chain [1] start processing

14:34:58 - cmdstanpy - INFO - Chain [1] done processing

14:34:58 - cmdstanpy - INFO - Chain [1] start processing

14:34:58 - cmdstanpy - INFO - Chain [1] done processing

14:34:58 - cmdstanpy - INFO - Chain [1] start processing

14:34:58 - cmdstanpy - INFO - Chain [1] done processing

14:34:58 - cmdstanpy - INFO - Chain [1] start processing

14:34:58 - cmdstanpy - INFO - Chain [1] done processing

14:34:58 - cmdstanpy - INFO - Chain [1] start processing

14:34:59 - cmdstanpy - INFO - Chain [1] done processing

14:34:59 - cmdstanpy - INFO - Chain [1] start processing

14:34:59 - cmdstanpy - INFO - Chain [1] done processing

14:34:59 - cmdstanpy - INFO - Chain [1] start processing

14:34:59 - cmdstanpy - INFO - Chain [1] done processing

14:34:59 - cmdstanpy - INFO - Chain [1] start processing

14:34:59 - cmdstanpy - INFO - Chain [1] done processing

14:34:59 - cmdstanpy - INFO - Chain [1] start processing

14:35:00 - cmdstanpy - INFO - Chain [1] done processing

14:35:00 - cmdstanpy - INFO - Chain [1] start processing

14:35:00 - cmdstanpy - INFO - Chain [1] done processing

14:35:00 - cmdstanpy - INFO - Chain [1] start processing

14:35:00 - cmdstanpy - INFO - Chain [1] done processing

14:35:00 - cmdstanpy - INFO - Chain [1] start processing

14:35:00 - cmdstanpy - INFO - Chain [1] done processing

14:35:00 - cmdstanpy - INFO - Chain [1] start processing

14:35:00 - cmdstanpy - INFO - Chain [1] done processing

14:35:01 - cmdstanpy - INFO - Chain [1] start processing

14:35:01 - cmdstanpy - INFO - Chain [1] done processing

14:35:01 - cmdstanpy - INFO - Chain [1] start processing

14:35:01 - cmdstanpy - INFO - Chain [1] done processing

14:35:01 - cmdstanpy - INFO - Chain [1] start processing

14:35:01 - cmdstanpy - INFO - Chain [1] done processing

14:35:01 - cmdstanpy - INFO - Chain [1] start processing

14:35:01 - cmdstanpy - INFO - Chain [1] done processing

14:35:02 - cmdstanpy - INFO - Chain [1] start processing

14:35:02 - cmdstanpy - INFO - Chain [1] done processing

14:35:02 - cmdstanpy - INFO - Chain [1] start processing

14:35:02 - cmdstanpy - INFO - Chain [1] done processing

14:35:02 - cmdstanpy - INFO - Chain [1] start processing

14:35:02 - cmdstanpy - INFO - Chain [1] done processing

14:35:02 - cmdstanpy - INFO - Chain [1] start processing

14:35:02 - cmdstanpy - INFO - Chain [1] done processing

14:35:03 - cmdstanpy - INFO - Chain [1] start processing

14:35:03 - cmdstanpy - INFO - Chain [1] done processing

14:35:03 - cmdstanpy - INFO - Chain [1] start processing

14:35:03 - cmdstanpy - INFO - Chain [1] done processing

14:35:03 - cmdstanpy - INFO - Chain [1] start processing

14:35:03 - cmdstanpy - INFO - Chain [1] done processing

14:35:03 - cmdstanpy - INFO - Chain [1] start processing

14:35:03 - cmdstanpy - INFO - Chain [1] done processing

14:35:03 - cmdstanpy - INFO - Chain [1] start processing

14:35:04 - cmdstanpy - INFO - Chain [1] done processing

14:35:04 - cmdstanpy - INFO - Chain [1] start processing

14:35:04 - cmdstanpy - INFO - Chain [1] done processing

14:35:04 - cmdstanpy - INFO - Chain [1] start processing

14:35:04 - cmdstanpy - INFO - Chain [1] done processing

14:35:04 - cmdstanpy - INFO - Chain [1] start processing

14:35:04 - cmdstanpy - INFO - Chain [1] done processing

14:35:04 - cmdstanpy - INFO - Chain [1] start processing

14:35:05 - cmdstanpy - INFO - Chain [1] done processing

14:35:05 - cmdstanpy - INFO - Chain [1] start processing

14:35:05 - cmdstanpy - INFO - Chain [1] done processing

14:35:05 - cmdstanpy - INFO - Chain [1] start processing

14:35:05 - cmdstanpy - INFO - Chain [1] done processing

14:35:05 - cmdstanpy - INFO - Chain [1] start processing

14:35:05 - cmdstanpy - INFO - Chain [1] done processing

14:35:05 - cmdstanpy - INFO - Chain [1] start processing

14:35:06 - cmdstanpy - INFO - Chain [1] done processing

14:35:06 - cmdstanpy - INFO - Chain [1] start processing

14:35:06 - cmdstanpy - INFO - Chain [1] done processing

[{'group_id': 'GROCERY',
  'rmse': np.float64(10793.93359301018),
  'mae': 10793.922552168078,
  'mape': np.float64(0.2494084642409935)},
 {'group_id': 'GROCERY',
  'rmse': np.float64(8244.980902236568),
  'mae': 7856.179666764267,
  'mape': np.float64(0.17408894280635245)},
 {'group_id': 'GROCERY',
  'rmse': np.float64(11374.45382645973),
  'mae': 11363.533591020387,
  'mape': np.float64(0.26251767918542845)}]

In [6]:
# Make each group_id continuous in time_idx for TFT only
forecast_df_tft = forecast_df.sort_values(["group_id","time_idx"]).copy()

all_groups = forecast_df_tft["group_id"].unique()
t_min = int(forecast_df_tft["time_idx"].min())
t_max = int(forecast_df_tft["time_idx"].max())

full_index = pd.MultiIndex.from_product(
    [all_groups, np.arange(t_min, t_max+1)],
    names=["group_id","time_idx"]
)

forecast_df_tft = (
    forecast_df_tft.set_index(["group_id","time_idx"])
                   .reindex(full_index)
                   .reset_index()
)

# fill known covariates theo group
known_cols = ["avg_price","discount_rate","promo_display","promo_mailer","weekofyear","week_no"]
for c in known_cols:
    if c in forecast_df_tft.columns:
        forecast_df_tft[c] = (
            forecast_df_tft.groupby("group_id")[c]
                           .ffill()
                           .bfill()
        )

# fill target tuần thiếu (chọn 0 cho chuẩn retail)
forecast_df_tft["target"] = forecast_df_tft["target"].fillna(0)

# safety weekofyear nếu NA
forecast_df_tft["weekofyear"] = (
    forecast_df_tft["weekofyear"]
    .fillna(forecast_df_tft["time_idx"] % 52)
    .astype(int)
)

forecast_df_tft.head()

,group_id,time_idx,week_no,qty,target,retail_disc,coupon_disc,coupon_match_disc,avg_price,promo_display,promo_mailer,promo_price_red,total_disc,gross_sales,discount_rate,weekofyear
0,AUTOMOTIVE,0,1.0,1.0,4.99,0.0,0.0,0.0,4.99,0.0,0.0,0.0,0.0,4.99,0.0,1
1,AUTOMOTIVE,1,1.0,NaN,0.00,NaN,NaN,NaN,4.99,0.0,0.0,NaN,NaN,NaN,0.0,1
2,AUTOMOTIVE,2,1.0,NaN,0.00,NaN,NaN,NaN,4.99,0.0,0.0,NaN,NaN,NaN,0.0,1
3,AUTOMOTIVE,3,1.0,NaN,0.00,NaN,NaN,NaN,4.99,0.0,0.0,NaN,NaN,NaN,0.0,1
4,AUTOMOTIVE,4,1.0,NaN,0.00,NaN,NaN,NaN,4.99,0.0,0.0,NaN,NaN,NaN,0.0,1

In [7]:
import torch
from lightning.pytorch import Trainer, seed_everything   # <-- đổi dòng này
from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.data import GroupNormalizer
from pytorch_forecasting.metrics import QuantileLoss


seed_everything(42)

max_encoder_length = 12
max_prediction_length = 2
training_cutoff = forecast_df_tft.time_idx.max() - max_prediction_length

training = TimeSeriesDataSet(
    forecast_df_tft[forecast_df_tft.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="target",
    group_ids=["group_id"],
    max_encoder_length=max_encoder_length,
    max_prediction_length=max_prediction_length,
    static_categoricals=["group_id"],

    # KNOWN covariates (promo/price biết trước)
    time_varying_known_reals=[
        "time_idx","weekofyear",
        "avg_price","discount_rate",
        "promo_display","promo_mailer"
    ],

    # UNKNOWN: chỉ target
    time_varying_unknown_reals=["target"],

    target_normalizer=GroupNormalizer(groups=["group_id"]),
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)

valid = TimeSeriesDataSet.from_dataset(
    training, forecast_df_tft, predict=True, stop_randomization=True
)

train_loader = training.to_dataloader(train=True, batch_size=64, num_workers=0)
valid_loader = valid.to_dataloader(train=False, batch_size=64, num_workers=0)

tft = TemporalFusionTransformer.from_dataset(
    training,
    hidden_size=64, attention_head_size=4, dropout=0.1,
    hidden_continuous_size=64, learning_rate=1e-3,
    loss=QuantileLoss()
)

trainer = Trainer(
    max_epochs=30,
    accelerator="auto",
    devices="auto",
    gradient_clip_val=0.1
)

trainer.fit(tft, train_loader, valid_loader)

Seed set to 42

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: False, used: False

TPU available: False, using: 0 TPU cores

   | Name                               | Type                            | Params | Mode
------------------------------------------------------------------------------------------------
0  | loss                               | QuantileLoss                    | 0      | train
1  | logging_metrics                    | ModuleList                      | 0      | train
2  | input_embeddings                   | MultiEmbedding                  | 432    | train
3  | prescalers                         | ModuleDict                      | 1.4 K  | train
4  | static_variable_selection          | VariableSelectionNetwork        | 51.8 K | train
5  | encoder_variable_selection         | VariableSelectionNetwork        | 140 K  | train
6  | decoder_variable_selection         | VariableSelectionNetwork        | 122 K  | train
7  | static_context_variable_selection  | GatedResidualNetwork            | 16.8 K | train
8  | static_context_initial_hidden_lstm | GatedResidualNetwork            | 16.8 K | train
9  | static_context_initial_cell_lstm   | GatedResidualNetwork            | 16.8 K | train
10 | static_context_enrichment          | GatedResidualNetwork            | 16.8 K | train
11 | lstm_encoder                       | LSTM                            | 33.3 K | train
12 | lstm_decoder                       | LSTM                            | 33.3 K | train
13 | post_lstm_gate_encoder             | GatedLinearUnit                 | 8.3 K  | train
14 | post_lstm_add_norm_encoder         | AddNorm                         | 128    | train
15 | static_enrichment                  | GatedResidualNetwork            | 20.9 K | train
16 | multihead_attn                     | InterpretableMultiHeadAttention | 10.4 K | train
17 | post_attn_gate_norm                | GateAddNorm                     | 8.4 K  | train
18 | pos_wise_ff                        | GatedResidualNetwork            | 16.8 K | train
19 | pre_output_gate_norm               | GateAddNorm                     | 8.4 K  | train
20 | output_layer                       | Linear                          | 455    | train
------------------------------------------------------------------------------------------------
520 K     Trainable params
0         Non-trainable params
520 K     Total params
2.083     Total estimated model params size (MB)
357       Modules in train mode
0         Modules in eval mode

Sanity Checking: |                                                                                                                   | 0/? [00:00<?, ?it/s]

Sanity Checking: |                                                                                                                   | 0/? [00:00<?, ?it/s]

Sanity Checking DataLoader 0:   0%|                                                                                                  | 0/1 [00:00<?, ?it/s]

Sanity Checking DataLoader 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.32it/s]

Training: |                                                                                                                          | 0/? [00:00<?, ?it/s]

Training: |                                                                                                                          | 0/? [00:00<?, ?it/s]

Epoch 0:   0%|                                                                                                                      | 0/18 [00:00<?, ?it/s]

Epoch 0:   6%|██████                                                                                                        | 1/18 [00:00<00:02,  7.46it/s]

Epoch 0:   6%|████▎                                                                        | 1/18 [00:00<00:02,  7.46it/s, v_num=19, train_loss_step=569.0]

Epoch 0:  11%|████████▌                                                                    | 2/18 [00:00<00:01,  8.24it/s, v_num=19, train_loss_step=569.0]

Epoch 0:  11%|████████▌                                                                    | 2/18 [00:00<00:01,  8.24it/s, v_num=19, train_loss_step=432.0]

Epoch 0:  17%|████████████▊                                                                | 3/18 [00:00<00:01,  8.08it/s, v_num=19, train_loss_step=432.0]

Epoch 0:  17%|████████████▊                                                                | 3/18 [00:00<00:01,  8.08it/s, v_num=19, train_loss_step=168.0]

Epoch 0:  22%|█████████████████                                                            | 4/18 [00:00<00:01,  8.16it/s, v_num=19, train_loss_step=168.0]

Epoch 0:  22%|█████████████████                                                            | 4/18 [00:00<00:01,  8.13it/s, v_num=19, train_loss_step=166.0]

Epoch 0:  28%|█████████████████████▍                                                       | 5/18 [00:00<00:01,  8.20it/s, v_num=19, train_loss_step=166.0]

Epoch 0:  28%|█████████████████████▍                                                       | 5/18 [00:00<00:01,  8.17it/s, v_num=19, train_loss_step=121.0]

Epoch 0:  33%|█████████████████████████▋                                                   | 6/18 [00:00<00:01,  8.23it/s, v_num=19, train_loss_step=121.0]

Epoch 0:  33%|█████████████████████████▋                                                   | 6/18 [00:00<00:01,  8.23it/s, v_num=19, train_loss_step=157.0]

Epoch 0:  39%|█████████████████████████████▉                                               | 7/18 [00:00<00:01,  8.27it/s, v_num=19, train_loss_step=157.0]

Epoch 0:  39%|█████████████████████████████▉                                               | 7/18 [00:00<00:01,  8.27it/s, v_num=19, train_loss_step=166.0]

Epoch 0:  44%|██████████████████████████████████▏                                          | 8/18 [00:00<00:01,  8.34it/s, v_num=19, train_loss_step=166.0]

Epoch 0:  44%|██████████████████████████████████▏                                          | 8/18 [00:00<00:01,  8.34it/s, v_num=19, train_loss_step=87.10]

Epoch 0:  50%|██████████████████████████████████████▌                                      | 9/18 [00:01<00:01,  8.50it/s, v_num=19, train_loss_step=87.10]

Epoch 0:  50%|██████████████████████████████████████▌                                      | 9/18 [00:01<00:01,  8.48it/s, v_num=19, train_loss_step=73.40]

Epoch 0:  56%|██████████████████████████████████████████▏                                 | 10/18 [00:01<00:00,  8.46it/s, v_num=19, train_loss_step=73.40]

Epoch 0:  56%|██████████████████████████████████████████▏                                 | 10/18 [00:01<00:00,  8.45it/s, v_num=19, train_loss_step=181.0]

Epoch 0:  61%|██████████████████████████████████████████████▍                             | 11/18 [00:01<00:00,  8.54it/s, v_num=19, train_loss_step=181.0]

Epoch 0:  61%|██████████████████████████████████████████████▍                             | 11/18 [00:01<00:00,  8.54it/s, v_num=19, train_loss_step=151.0]

Epoch 0:  67%|██████████████████████████████████████████████████▋                         | 12/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=151.0]

Epoch 0:  67%|██████████████████████████████████████████████████▋                         | 12/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=116.0]

Epoch 0:  72%|██████████████████████████████████████████████████████▉                     | 13/18 [00:01<00:00,  8.49it/s, v_num=19, train_loss_step=116.0]

Epoch 0:  72%|██████████████████████████████████████████████████████▉                     | 13/18 [00:01<00:00,  8.48it/s, v_num=19, train_loss_step=68.60]

Epoch 0:  78%|███████████████████████████████████████████████████████████                 | 14/18 [00:01<00:00,  8.49it/s, v_num=19, train_loss_step=68.60]

Epoch 0:  78%|███████████████████████████████████████████████████████████                 | 14/18 [00:01<00:00,  8.49it/s, v_num=19, train_loss_step=133.0]

Epoch 0:  83%|███████████████████████████████████████████████████████████████▎            | 15/18 [00:01<00:00,  8.53it/s, v_num=19, train_loss_step=133.0]

Epoch 0:  83%|███████████████████████████████████████████████████████████████▎            | 15/18 [00:01<00:00,  8.53it/s, v_num=19, train_loss_step=163.0]

Epoch 0:  89%|███████████████████████████████████████████████████████████████████▌        | 16/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=163.0]

Epoch 0:  89%|███████████████████████████████████████████████████████████████████▌        | 16/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=117.0]

Epoch 0:  94%|███████████████████████████████████████████████████████████████████████▊    | 17/18 [00:01<00:00,  8.60it/s, v_num=19, train_loss_step=117.0]

Epoch 0:  94%|███████████████████████████████████████████████████████████████████████▊    | 17/18 [00:01<00:00,  8.60it/s, v_num=19, train_loss_step=135.0]

Epoch 0: 100%|████████████████████████████████████████████████████████████████████████████| 18/18 [00:02<00:00,  8.57it/s, v_num=19, train_loss_step=135.0]

Epoch 0: 100%|████████████████████████████████████████████████████████████████████████████| 18/18 [00:02<00:00,  8.56it/s, v_num=19, train_loss_step=98.90]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.36it/s]

Epoch 0: 100%|████████████████████████████████████████████████████████████| 18/18 [00:02<00:00,  8.29it/s, v_num=19, train_loss_step=98.90, val_loss=911.0]

Epoch 0: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.27it/s, v_num=19, train_loss_step=98.90, val_loss=911.0, train_loss_epoch=172.0]

Epoch 0:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=98.90, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=98.90, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:   6%|██                                   | 1/18 [00:00<00:01,  8.54it/s, v_num=19, train_loss_step=98.90, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:   6%|██                                   | 1/18 [00:00<00:02,  8.40it/s, v_num=19, train_loss_step=96.50, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  11%|████                                 | 2/18 [00:00<00:01,  8.75it/s, v_num=19, train_loss_step=96.50, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  11%|████                                 | 2/18 [00:00<00:01,  8.75it/s, v_num=19, train_loss_step=135.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  17%|██████▏                              | 3/18 [00:00<00:01,  8.89it/s, v_num=19, train_loss_step=135.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  17%|██████▏                              | 3/18 [00:00<00:01,  8.83it/s, v_num=19, train_loss_step=131.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  22%|████████▏                            | 4/18 [00:00<00:01,  8.95it/s, v_num=19, train_loss_step=131.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  22%|████████▏                            | 4/18 [00:00<00:01,  8.95it/s, v_num=19, train_loss_step=106.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.77it/s, v_num=19, train_loss_step=106.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.74it/s, v_num=19, train_loss_step=219.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.68it/s, v_num=19, train_loss_step=219.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.66it/s, v_num=19, train_loss_step=117.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.58it/s, v_num=19, train_loss_step=117.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.55it/s, v_num=19, train_loss_step=71.50, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.64it/s, v_num=19, train_loss_step=71.50, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.62it/s, v_num=19, train_loss_step=72.60, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.64it/s, v_num=19, train_loss_step=72.60, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.63it/s, v_num=19, train_loss_step=137.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  56%|████████████████████                | 10/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=137.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  56%|████████████████████                | 10/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=110.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.64it/s, v_num=19, train_loss_step=110.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.62it/s, v_num=19, train_loss_step=140.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.76it/s, v_num=19, train_loss_step=140.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.66it/s, v_num=19, train_loss_step=87.00, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.72it/s, v_num=19, train_loss_step=87.00, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.71it/s, v_num=19, train_loss_step=92.70, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.80it/s, v_num=19, train_loss_step=92.70, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.80it/s, v_num=19, train_loss_step=110.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.78it/s, v_num=19, train_loss_step=110.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.78it/s, v_num=19, train_loss_step=135.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.80it/s, v_num=19, train_loss_step=135.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.79it/s, v_num=19, train_loss_step=87.60, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  94%|██████████████████████████████████  | 17/18 [00:01<00:00,  8.84it/s, v_num=19, train_loss_step=87.60, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1:  94%|██████████████████████████████████  | 17/18 [00:01<00:00,  8.84it/s, v_num=19, train_loss_step=119.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.84it/s, v_num=19, train_loss_step=119.0, val_loss=911.0, train_loss_epoch=172.0]

Epoch 1: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.83it/s, v_num=19, train_loss_step=151.0, val_loss=911.0, train_loss_epoch=172.0]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.19it/s]

Epoch 1: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.57it/s, v_num=19, train_loss_step=151.0, val_loss=941.0, train_loss_epoch=172.0]

Epoch 1: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.55it/s, v_num=19, train_loss_step=151.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 1:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=151.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=151.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:   6%|██                                   | 1/18 [00:00<00:01,  8.84it/s, v_num=19, train_loss_step=151.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:   6%|██                                   | 1/18 [00:00<00:01,  8.84it/s, v_num=19, train_loss_step=120.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  11%|████                                 | 2/18 [00:00<00:01,  8.97it/s, v_num=19, train_loss_step=120.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  11%|████                                 | 2/18 [00:00<00:01,  8.97it/s, v_num=19, train_loss_step=129.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  17%|██████▏                              | 3/18 [00:00<00:01,  9.10it/s, v_num=19, train_loss_step=129.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  17%|██████▏                              | 3/18 [00:00<00:01,  9.10it/s, v_num=19, train_loss_step=94.30, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  22%|████████▏                            | 4/18 [00:00<00:01,  9.13it/s, v_num=19, train_loss_step=94.30, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  22%|████████▏                            | 4/18 [00:00<00:01,  9.13it/s, v_num=19, train_loss_step=67.60, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  28%|██████████▎                          | 5/18 [00:00<00:01,  9.14it/s, v_num=19, train_loss_step=67.60, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  28%|██████████▎                          | 5/18 [00:00<00:01,  9.14it/s, v_num=19, train_loss_step=77.00, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  33%|████████████▎                        | 6/18 [00:00<00:01,  9.17it/s, v_num=19, train_loss_step=77.00, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  33%|████████████▎                        | 6/18 [00:00<00:01,  9.17it/s, v_num=19, train_loss_step=101.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.97it/s, v_num=19, train_loss_step=101.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.95it/s, v_num=19, train_loss_step=119.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.86it/s, v_num=19, train_loss_step=119.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.86it/s, v_num=19, train_loss_step=95.30, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  50%|██████████████████▌                  | 9/18 [00:00<00:00,  9.02it/s, v_num=19, train_loss_step=95.30, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  50%|██████████████████▌                  | 9/18 [00:00<00:00,  9.02it/s, v_num=19, train_loss_step=96.80, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  56%|████████████████████                | 10/18 [00:01<00:00,  8.90it/s, v_num=19, train_loss_step=96.80, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  56%|████████████████████                | 10/18 [00:01<00:00,  8.90it/s, v_num=19, train_loss_step=154.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.91it/s, v_num=19, train_loss_step=154.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.90it/s, v_num=19, train_loss_step=51.80, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.92it/s, v_num=19, train_loss_step=51.80, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.91it/s, v_num=19, train_loss_step=78.50, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.89it/s, v_num=19, train_loss_step=78.50, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.88it/s, v_num=19, train_loss_step=112.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.89it/s, v_num=19, train_loss_step=112.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.88it/s, v_num=19, train_loss_step=79.70, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=79.70, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.56it/s, v_num=19, train_loss_step=109.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.57it/s, v_num=19, train_loss_step=109.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.56it/s, v_num=19, train_loss_step=179.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  94%|██████████████████████████████████  | 17/18 [00:01<00:00,  8.61it/s, v_num=19, train_loss_step=179.0, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2:  94%|██████████████████████████████████  | 17/18 [00:01<00:00,  8.60it/s, v_num=19, train_loss_step=74.00, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.63it/s, v_num=19, train_loss_step=74.00, val_loss=941.0, train_loss_epoch=118.0]

Epoch 2: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.63it/s, v_num=19, train_loss_step=130.0, val_loss=941.0, train_loss_epoch=118.0]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.82it/s]

Epoch 2: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.37it/s, v_num=19, train_loss_step=130.0, val_loss=939.0, train_loss_epoch=118.0]

Epoch 2: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.35it/s, v_num=19, train_loss_step=130.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 2:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=130.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=130.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:   6%|██                                   | 1/18 [00:00<00:02,  7.87it/s, v_num=19, train_loss_step=130.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:   6%|██                                   | 1/18 [00:00<00:02,  7.81it/s, v_num=19, train_loss_step=105.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  11%|████                                 | 2/18 [00:00<00:01,  8.22it/s, v_num=19, train_loss_step=105.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  11%|████                                 | 2/18 [00:00<00:02,  8.00it/s, v_num=19, train_loss_step=212.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  17%|██████▏                              | 3/18 [00:00<00:01,  8.31it/s, v_num=19, train_loss_step=212.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  17%|██████▏                              | 3/18 [00:00<00:01,  8.31it/s, v_num=19, train_loss_step=128.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  22%|████████▏                            | 4/18 [00:00<00:01,  8.17it/s, v_num=19, train_loss_step=128.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  22%|████████▏                            | 4/18 [00:00<00:01,  8.17it/s, v_num=19, train_loss_step=55.10, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.07it/s, v_num=19, train_loss_step=55.10, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.04it/s, v_num=19, train_loss_step=113.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.02it/s, v_num=19, train_loss_step=113.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.02it/s, v_num=19, train_loss_step=91.70, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.05it/s, v_num=19, train_loss_step=91.70, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.03it/s, v_num=19, train_loss_step=89.60, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.06it/s, v_num=19, train_loss_step=89.60, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.06it/s, v_num=19, train_loss_step=82.50, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.15it/s, v_num=19, train_loss_step=82.50, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.15it/s, v_num=19, train_loss_step=49.50, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  56%|████████████████████                | 10/18 [00:01<00:00,  8.13it/s, v_num=19, train_loss_step=49.50, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  56%|████████████████████                | 10/18 [00:01<00:00,  8.12it/s, v_num=19, train_loss_step=133.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.16it/s, v_num=19, train_loss_step=133.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.15it/s, v_num=19, train_loss_step=122.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.13it/s, v_num=19, train_loss_step=122.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.11it/s, v_num=19, train_loss_step=49.10, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.21it/s, v_num=19, train_loss_step=49.10, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.21it/s, v_num=19, train_loss_step=127.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.26it/s, v_num=19, train_loss_step=127.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.25it/s, v_num=19, train_loss_step=79.30, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.26it/s, v_num=19, train_loss_step=79.30, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.26it/s, v_num=19, train_loss_step=104.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.24it/s, v_num=19, train_loss_step=104.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.23it/s, v_num=19, train_loss_step=123.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  94%|██████████████████████████████████  | 17/18 [00:02<00:00,  8.29it/s, v_num=19, train_loss_step=123.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3:  94%|██████████████████████████████████  | 17/18 [00:02<00:00,  8.29it/s, v_num=19, train_loss_step=132.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.30it/s, v_num=19, train_loss_step=132.0, val_loss=939.0, train_loss_epoch=104.0]

Epoch 3: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.30it/s, v_num=19, train_loss_step=124.0, val_loss=939.0, train_loss_epoch=104.0]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.90it/s]

Epoch 3: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.00it/s, v_num=19, train_loss_step=124.0, val_loss=932.0, train_loss_epoch=104.0]

Epoch 3: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  7.99it/s, v_num=19, train_loss_step=124.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 3:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=124.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=124.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:   6%|██                                   | 1/18 [00:00<00:01,  8.50it/s, v_num=19, train_loss_step=124.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:   6%|██                                   | 1/18 [00:00<00:01,  8.50it/s, v_num=19, train_loss_step=124.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  11%|████                                 | 2/18 [00:00<00:01,  8.80it/s, v_num=19, train_loss_step=124.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  11%|████                                 | 2/18 [00:00<00:01,  8.74it/s, v_num=19, train_loss_step=96.00, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  17%|██████▏                              | 3/18 [00:00<00:01,  8.82it/s, v_num=19, train_loss_step=96.00, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  17%|██████▏                              | 3/18 [00:00<00:01,  8.69it/s, v_num=19, train_loss_step=113.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  22%|████████▏                            | 4/18 [00:00<00:01,  8.90it/s, v_num=19, train_loss_step=113.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  22%|████████▏                            | 4/18 [00:00<00:01,  8.76it/s, v_num=19, train_loss_step=96.40, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.80it/s, v_num=19, train_loss_step=96.40, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.70it/s, v_num=19, train_loss_step=106.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.49it/s, v_num=19, train_loss_step=106.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.47it/s, v_num=19, train_loss_step=154.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.49it/s, v_num=19, train_loss_step=154.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.49it/s, v_num=19, train_loss_step=56.60, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.48it/s, v_num=19, train_loss_step=56.60, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.48it/s, v_num=19, train_loss_step=119.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.48it/s, v_num=19, train_loss_step=119.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.48it/s, v_num=19, train_loss_step=145.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  56%|████████████████████                | 10/18 [00:01<00:00,  8.39it/s, v_num=19, train_loss_step=145.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  56%|████████████████████                | 10/18 [00:01<00:00,  8.38it/s, v_num=19, train_loss_step=101.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.48it/s, v_num=19, train_loss_step=101.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  61%|██████████████████████              | 11/18 [00:01<00:00,  8.48it/s, v_num=19, train_loss_step=94.30, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.48it/s, v_num=19, train_loss_step=94.30, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  67%|████████████████████████            | 12/18 [00:01<00:00,  8.48it/s, v_num=19, train_loss_step=92.70, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.48it/s, v_num=19, train_loss_step=92.70, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  72%|██████████████████████████          | 13/18 [00:01<00:00,  8.48it/s, v_num=19, train_loss_step=130.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.41it/s, v_num=19, train_loss_step=130.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  78%|████████████████████████████        | 14/18 [00:01<00:00,  8.40it/s, v_num=19, train_loss_step=69.30, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.40it/s, v_num=19, train_loss_step=69.30, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  8.39it/s, v_num=19, train_loss_step=99.90, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.35it/s, v_num=19, train_loss_step=99.90, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  8.33it/s, v_num=19, train_loss_step=157.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  94%|██████████████████████████████████  | 17/18 [00:02<00:00,  8.33it/s, v_num=19, train_loss_step=157.0, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4:  94%|██████████████████████████████████  | 17/18 [00:02<00:00,  8.33it/s, v_num=19, train_loss_step=59.70, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.31it/s, v_num=19, train_loss_step=59.70, val_loss=932.0, train_loss_epoch=107.0]

Epoch 4: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.31it/s, v_num=19, train_loss_step=129.0, val_loss=932.0, train_loss_epoch=107.0]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.92it/s]

Epoch 4: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.05it/s, v_num=19, train_loss_step=129.0, val_loss=928.0, train_loss_epoch=107.0]

Epoch 4: 100%|████████████████████████████████████| 18/18 [00:02<00:00,  8.05it/s, v_num=19, train_loss_step=129.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 4:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=129.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=129.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:   6%|██                                   | 1/18 [00:00<00:02,  8.00it/s, v_num=19, train_loss_step=129.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:   6%|██                                   | 1/18 [00:00<00:02,  8.00it/s, v_num=19, train_loss_step=46.80, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  11%|████                                 | 2/18 [00:00<00:02,  7.95it/s, v_num=19, train_loss_step=46.80, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  11%|████                                 | 2/18 [00:00<00:02,  7.92it/s, v_num=19, train_loss_step=48.60, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  17%|██████▏                              | 3/18 [00:00<00:01,  8.10it/s, v_num=19, train_loss_step=48.60, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  17%|██████▏                              | 3/18 [00:00<00:01,  8.06it/s, v_num=19, train_loss_step=94.10, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  22%|████████▏                            | 4/18 [00:00<00:01,  8.00it/s, v_num=19, train_loss_step=94.10, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  22%|████████▏                            | 4/18 [00:00<00:01,  7.76it/s, v_num=19, train_loss_step=156.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.09it/s, v_num=19, train_loss_step=156.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  28%|██████████▎                          | 5/18 [00:00<00:01,  8.09it/s, v_num=19, train_loss_step=107.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.32it/s, v_num=19, train_loss_step=107.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  33%|████████████▎                        | 6/18 [00:00<00:01,  8.32it/s, v_num=19, train_loss_step=69.30, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.65it/s, v_num=19, train_loss_step=69.30, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  39%|██████████████▍                      | 7/18 [00:00<00:01,  8.62it/s, v_num=19, train_loss_step=132.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.75it/s, v_num=19, train_loss_step=132.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  44%|████████████████▍                    | 8/18 [00:00<00:01,  8.75it/s, v_num=19, train_loss_step=141.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.90it/s, v_num=19, train_loss_step=141.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  50%|██████████████████▌                  | 9/18 [00:01<00:01,  8.89it/s, v_num=19, train_loss_step=44.80, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  56%|████████████████████                | 10/18 [00:01<00:00,  9.08it/s, v_num=19, train_loss_step=44.80, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  56%|████████████████████                | 10/18 [00:01<00:00,  9.07it/s, v_num=19, train_loss_step=86.50, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  61%|██████████████████████              | 11/18 [00:01<00:00,  9.17it/s, v_num=19, train_loss_step=86.50, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  61%|██████████████████████              | 11/18 [00:01<00:00,  9.17it/s, v_num=19, train_loss_step=116.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  67%|████████████████████████            | 12/18 [00:01<00:00,  9.31it/s, v_num=19, train_loss_step=116.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  67%|████████████████████████            | 12/18 [00:01<00:00,  9.20it/s, v_num=19, train_loss_step=132.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  72%|██████████████████████████          | 13/18 [00:01<00:00,  9.37it/s, v_num=19, train_loss_step=132.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  72%|██████████████████████████          | 13/18 [00:01<00:00,  9.35it/s, v_num=19, train_loss_step=115.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  78%|████████████████████████████        | 14/18 [00:01<00:00,  9.43it/s, v_num=19, train_loss_step=115.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  78%|████████████████████████████        | 14/18 [00:01<00:00,  9.42it/s, v_num=19, train_loss_step=105.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  9.53it/s, v_num=19, train_loss_step=105.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  83%|██████████████████████████████      | 15/18 [00:01<00:00,  9.53it/s, v_num=19, train_loss_step=82.50, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  9.47it/s, v_num=19, train_loss_step=82.50, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  89%|████████████████████████████████    | 16/18 [00:01<00:00,  9.47it/s, v_num=19, train_loss_step=168.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  94%|██████████████████████████████████  | 17/18 [00:01<00:00,  9.53it/s, v_num=19, train_loss_step=168.0, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5:  94%|██████████████████████████████████  | 17/18 [00:01<00:00,  9.52it/s, v_num=19, train_loss_step=95.70, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5: 100%|████████████████████████████████████| 18/18 [00:01<00:00,  9.60it/s, v_num=19, train_loss_step=95.70, val_loss=928.0, train_loss_epoch=108.0]

Epoch 5: 100%|████████████████████████████████████| 18/18 [00:01<00:00,  9.60it/s, v_num=19, train_loss_step=99.20, val_loss=928.0, train_loss_epoch=108.0]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.41it/s]

Epoch 5: 100%|████████████████████████████████████| 18/18 [00:01<00:00,  9.29it/s, v_num=19, train_loss_step=99.20, val_loss=959.0, train_loss_epoch=108.0]

Epoch 5: 100%|████████████████████████████████████| 18/18 [00:01<00:00,  9.26it/s, v_num=19, train_loss_step=99.20, val_loss=959.0, train_loss_epoch=102.0]

Epoch 5:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=99.20, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=99.20, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:   6%|██                                   | 1/18 [00:00<00:01,  9.56it/s, v_num=19, train_loss_step=99.20, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:   6%|██                                   | 1/18 [00:00<00:01,  9.56it/s, v_num=19, train_loss_step=111.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  11%|████                                 | 2/18 [00:00<00:01, 11.21it/s, v_num=19, train_loss_step=111.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  11%|████                                 | 2/18 [00:00<00:01, 10.30it/s, v_num=19, train_loss_step=64.10, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  17%|██████▏                              | 3/18 [00:00<00:01, 10.17it/s, v_num=19, train_loss_step=64.10, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  17%|██████▏                              | 3/18 [00:00<00:01, 10.11it/s, v_num=19, train_loss_step=157.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  22%|████████▏                            | 4/18 [00:00<00:01,  9.72it/s, v_num=19, train_loss_step=157.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  22%|████████▏                            | 4/18 [00:00<00:01,  9.72it/s, v_num=19, train_loss_step=103.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  28%|██████████▎                          | 5/18 [00:00<00:01, 10.04it/s, v_num=19, train_loss_step=103.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  28%|██████████▎                          | 5/18 [00:00<00:01, 10.00it/s, v_num=19, train_loss_step=106.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.20it/s, v_num=19, train_loss_step=106.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.20it/s, v_num=19, train_loss_step=95.00, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  39%|██████████████▍                      | 7/18 [00:00<00:01, 10.34it/s, v_num=19, train_loss_step=95.00, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  39%|██████████████▍                      | 7/18 [00:00<00:01, 10.34it/s, v_num=19, train_loss_step=67.70, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  44%|████████████████▍                    | 8/18 [00:00<00:00, 10.31it/s, v_num=19, train_loss_step=67.70, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  44%|████████████████▍                    | 8/18 [00:00<00:00, 10.29it/s, v_num=19, train_loss_step=92.80, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.33it/s, v_num=19, train_loss_step=92.80, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.31it/s, v_num=19, train_loss_step=113.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  56%|████████████████████                | 10/18 [00:00<00:00, 10.38it/s, v_num=19, train_loss_step=113.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  56%|████████████████████                | 10/18 [00:00<00:00, 10.38it/s, v_num=19, train_loss_step=86.20, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  61%|██████████████████████              | 11/18 [00:01<00:00, 10.47it/s, v_num=19, train_loss_step=86.20, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  61%|██████████████████████              | 11/18 [00:01<00:00, 10.47it/s, v_num=19, train_loss_step=81.10, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  67%|████████████████████████            | 12/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=81.10, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  67%|████████████████████████            | 12/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=43.70, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  72%|██████████████████████████          | 13/18 [00:01<00:00, 10.59it/s, v_num=19, train_loss_step=43.70, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  72%|██████████████████████████          | 13/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=94.70, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.65it/s, v_num=19, train_loss_step=94.70, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.65it/s, v_num=19, train_loss_step=119.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=119.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.61it/s, v_num=19, train_loss_step=125.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.67it/s, v_num=19, train_loss_step=125.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.67it/s, v_num=19, train_loss_step=85.40, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.77it/s, v_num=19, train_loss_step=85.40, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.77it/s, v_num=19, train_loss_step=128.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.75it/s, v_num=19, train_loss_step=128.0, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.75it/s, v_num=19, train_loss_step=97.40, val_loss=959.0, train_loss_epoch=102.0]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.74it/s]

Epoch 6: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.36it/s, v_num=19, train_loss_step=97.40, val_loss=959.0, train_loss_epoch=102.0]

Epoch 6: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=97.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 6:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=97.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=97.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:   6%|██                                   | 1/18 [00:00<00:01, 12.61it/s, v_num=19, train_loss_step=97.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:   6%|██                                   | 1/18 [00:00<00:01, 12.61it/s, v_num=19, train_loss_step=70.50, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  11%|████                                 | 2/18 [00:00<00:01, 11.48it/s, v_num=19, train_loss_step=70.50, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  11%|████                                 | 2/18 [00:00<00:01, 11.48it/s, v_num=19, train_loss_step=119.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  17%|██████▏                              | 3/18 [00:00<00:01, 11.15it/s, v_num=19, train_loss_step=119.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  17%|██████▏                              | 3/18 [00:00<00:01, 11.15it/s, v_num=19, train_loss_step=53.80, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  22%|████████▏                            | 4/18 [00:00<00:01, 10.98it/s, v_num=19, train_loss_step=53.80, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  22%|████████▏                            | 4/18 [00:00<00:01, 10.98it/s, v_num=19, train_loss_step=166.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  28%|██████████▎                          | 5/18 [00:00<00:01, 11.18it/s, v_num=19, train_loss_step=166.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  28%|██████████▎                          | 5/18 [00:00<00:01, 11.18it/s, v_num=19, train_loss_step=53.60, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.83it/s, v_num=19, train_loss_step=53.60, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.83it/s, v_num=19, train_loss_step=104.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  39%|██████████████▍                      | 7/18 [00:00<00:00, 11.05it/s, v_num=19, train_loss_step=104.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  39%|██████████████▍                      | 7/18 [00:00<00:00, 11.05it/s, v_num=19, train_loss_step=118.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  44%|████████████████▍                    | 8/18 [00:00<00:00, 11.01it/s, v_num=19, train_loss_step=118.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  44%|████████████████▍                    | 8/18 [00:00<00:00, 11.01it/s, v_num=19, train_loss_step=145.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.99it/s, v_num=19, train_loss_step=145.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.99it/s, v_num=19, train_loss_step=91.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  56%|████████████████████                | 10/18 [00:00<00:00, 11.01it/s, v_num=19, train_loss_step=91.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  56%|████████████████████                | 10/18 [00:00<00:00, 10.98it/s, v_num=19, train_loss_step=89.20, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  61%|██████████████████████              | 11/18 [00:00<00:00, 11.06it/s, v_num=19, train_loss_step=89.20, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  61%|██████████████████████              | 11/18 [00:00<00:00, 11.04it/s, v_num=19, train_loss_step=137.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  67%|████████████████████████            | 12/18 [00:01<00:00, 11.09it/s, v_num=19, train_loss_step=137.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  67%|████████████████████████            | 12/18 [00:01<00:00, 11.07it/s, v_num=19, train_loss_step=76.20, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  72%|██████████████████████████          | 13/18 [00:01<00:00, 11.00it/s, v_num=19, train_loss_step=76.20, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  72%|██████████████████████████          | 13/18 [00:01<00:00, 10.98it/s, v_num=19, train_loss_step=106.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.83it/s, v_num=19, train_loss_step=106.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.83it/s, v_num=19, train_loss_step=108.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.84it/s, v_num=19, train_loss_step=108.0, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.84it/s, v_num=19, train_loss_step=74.90, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.81it/s, v_num=19, train_loss_step=74.90, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.80it/s, v_num=19, train_loss_step=75.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.87it/s, v_num=19, train_loss_step=75.40, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.85it/s, v_num=19, train_loss_step=90.50, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.95it/s, v_num=19, train_loss_step=90.50, val_loss=959.0, train_loss_epoch=98.40]

Epoch 7: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.95it/s, v_num=19, train_loss_step=58.00, val_loss=959.0, train_loss_epoch=98.40]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.29it/s]

Epoch 7: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=58.00, val_loss=957.0, train_loss_epoch=98.40]

Epoch 7: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=58.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 7:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=58.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=58.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:   6%|██                                   | 1/18 [00:00<00:01, 10.53it/s, v_num=19, train_loss_step=58.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:   6%|██                                   | 1/18 [00:00<00:01, 10.31it/s, v_num=19, train_loss_step=63.90, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  11%|████                                 | 2/18 [00:00<00:01, 10.79it/s, v_num=19, train_loss_step=63.90, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  11%|████                                 | 2/18 [00:00<00:01, 10.79it/s, v_num=19, train_loss_step=144.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  17%|██████▏                              | 3/18 [00:00<00:01, 10.64it/s, v_num=19, train_loss_step=144.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  17%|██████▏                              | 3/18 [00:00<00:01, 10.64it/s, v_num=19, train_loss_step=59.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  22%|████████▏                            | 4/18 [00:00<00:01, 10.09it/s, v_num=19, train_loss_step=59.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  22%|████████▏                            | 4/18 [00:00<00:01, 10.09it/s, v_num=19, train_loss_step=86.90, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  28%|██████████▎                          | 5/18 [00:00<00:01, 10.23it/s, v_num=19, train_loss_step=86.90, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  28%|██████████▎                          | 5/18 [00:00<00:01, 10.18it/s, v_num=19, train_loss_step=130.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.36it/s, v_num=19, train_loss_step=130.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.36it/s, v_num=19, train_loss_step=123.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  39%|██████████████▍                      | 7/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=123.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  39%|██████████████▍                      | 7/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=92.70, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  44%|████████████████▍                    | 8/18 [00:00<00:00, 10.41it/s, v_num=19, train_loss_step=92.70, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  44%|████████████████▍                    | 8/18 [00:00<00:00, 10.20it/s, v_num=19, train_loss_step=114.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.25it/s, v_num=19, train_loss_step=114.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.25it/s, v_num=19, train_loss_step=83.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  56%|████████████████████                | 10/18 [00:00<00:00, 10.23it/s, v_num=19, train_loss_step=83.00, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  56%|████████████████████                | 10/18 [00:00<00:00, 10.21it/s, v_num=19, train_loss_step=128.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  61%|██████████████████████              | 11/18 [00:01<00:00, 10.36it/s, v_num=19, train_loss_step=128.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  61%|██████████████████████              | 11/18 [00:01<00:00, 10.36it/s, v_num=19, train_loss_step=167.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  67%|████████████████████████            | 12/18 [00:01<00:00, 10.42it/s, v_num=19, train_loss_step=167.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  67%|████████████████████████            | 12/18 [00:01<00:00, 10.42it/s, v_num=19, train_loss_step=60.80, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  72%|██████████████████████████          | 13/18 [00:01<00:00, 10.48it/s, v_num=19, train_loss_step=60.80, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  72%|██████████████████████████          | 13/18 [00:01<00:00, 10.48it/s, v_num=19, train_loss_step=93.40, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.50it/s, v_num=19, train_loss_step=93.40, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=121.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=121.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=55.10, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.54it/s, v_num=19, train_loss_step=55.10, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=105.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.61it/s, v_num=19, train_loss_step=105.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.61it/s, v_num=19, train_loss_step=134.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.56it/s, v_num=19, train_loss_step=134.0, val_loss=957.0, train_loss_epoch=96.50]

Epoch 8: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.56it/s, v_num=19, train_loss_step=130.0, val_loss=957.0, train_loss_epoch=96.50]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 104.98it/s]

Epoch 8: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.22it/s, v_num=19, train_loss_step=130.0, val_loss=920.0, train_loss_epoch=96.50]

Epoch 8: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.19it/s, v_num=19, train_loss_step=130.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 8:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=130.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=130.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:   6%|██                                   | 1/18 [00:00<00:01,  9.84it/s, v_num=19, train_loss_step=130.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:   6%|██                                   | 1/18 [00:00<00:01,  9.65it/s, v_num=19, train_loss_step=106.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  11%|████                                 | 2/18 [00:00<00:01, 10.60it/s, v_num=19, train_loss_step=106.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  11%|████                                 | 2/18 [00:00<00:01, 10.48it/s, v_num=19, train_loss_step=116.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  17%|██████▏                              | 3/18 [00:00<00:01, 10.47it/s, v_num=19, train_loss_step=116.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  17%|██████▏                              | 3/18 [00:00<00:01, 10.47it/s, v_num=19, train_loss_step=88.30, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  22%|████████▏                            | 4/18 [00:00<00:01, 10.29it/s, v_num=19, train_loss_step=88.30, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  22%|████████▏                            | 4/18 [00:00<00:01, 10.23it/s, v_num=19, train_loss_step=67.80, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  28%|██████████▎                          | 5/18 [00:00<00:01, 10.42it/s, v_num=19, train_loss_step=67.80, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  28%|██████████▎                          | 5/18 [00:00<00:01, 10.37it/s, v_num=19, train_loss_step=59.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.39it/s, v_num=19, train_loss_step=59.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  33%|████████████▎                        | 6/18 [00:00<00:01, 10.39it/s, v_num=19, train_loss_step=72.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  39%|██████████████▍                      | 7/18 [00:00<00:01, 10.41it/s, v_num=19, train_loss_step=72.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  39%|██████████████▍                      | 7/18 [00:00<00:01, 10.41it/s, v_num=19, train_loss_step=140.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  44%|████████████████▍                    | 8/18 [00:00<00:00, 10.42it/s, v_num=19, train_loss_step=140.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  44%|████████████████▍                    | 8/18 [00:00<00:00, 10.42it/s, v_num=19, train_loss_step=92.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.62it/s, v_num=19, train_loss_step=92.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  50%|██████████████████▌                  | 9/18 [00:00<00:00, 10.43it/s, v_num=19, train_loss_step=59.10, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  56%|████████████████████                | 10/18 [00:00<00:00, 10.45it/s, v_num=19, train_loss_step=59.10, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  56%|████████████████████                | 10/18 [00:00<00:00, 10.45it/s, v_num=19, train_loss_step=95.50, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  61%|██████████████████████              | 11/18 [00:01<00:00, 10.45it/s, v_num=19, train_loss_step=95.50, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  61%|██████████████████████              | 11/18 [00:01<00:00, 10.45it/s, v_num=19, train_loss_step=55.30, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  67%|████████████████████████            | 12/18 [00:01<00:00, 10.46it/s, v_num=19, train_loss_step=55.30, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  67%|████████████████████████            | 12/18 [00:01<00:00, 10.46it/s, v_num=19, train_loss_step=68.30, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  72%|██████████████████████████          | 13/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=68.30, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  72%|██████████████████████████          | 13/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=145.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.27it/s, v_num=19, train_loss_step=145.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  78%|████████████████████████████        | 14/18 [00:01<00:00, 10.27it/s, v_num=19, train_loss_step=112.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.36it/s, v_num=19, train_loss_step=112.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  83%|██████████████████████████████      | 15/18 [00:01<00:00, 10.36it/s, v_num=19, train_loss_step=145.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.38it/s, v_num=19, train_loss_step=145.0, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  89%|████████████████████████████████    | 16/18 [00:01<00:00, 10.37it/s, v_num=19, train_loss_step=98.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.45it/s, v_num=19, train_loss_step=98.90, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9:  94%|██████████████████████████████████  | 17/18 [00:01<00:00, 10.45it/s, v_num=19, train_loss_step=69.60, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.48it/s, v_num=19, train_loss_step=69.60, val_loss=920.0, train_loss_epoch=105.0]

Epoch 9: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.48it/s, v_num=19, train_loss_step=104.0, val_loss=920.0, train_loss_epoch=105.0]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 43.45it/s]

Epoch 9: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.13it/s, v_num=19, train_loss_step=104.0, val_loss=925.0, train_loss_epoch=105.0]

Epoch 9: 100%|████████████████████████████████████| 18/18 [00:01<00:00, 10.11it/s, v_num=19, train_loss_step=104.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 9:   0%|                                             | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=104.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=104.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:   6%|██                                  | 1/18 [00:00<00:01, 10.12it/s, v_num=19, train_loss_step=104.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:   6%|██                                  | 1/18 [00:00<00:01, 10.12it/s, v_num=19, train_loss_step=65.80, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  11%|████                                | 2/18 [00:00<00:01, 11.38it/s, v_num=19, train_loss_step=65.80, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  11%|████                                | 2/18 [00:00<00:01, 10.43it/s, v_num=19, train_loss_step=98.10, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  17%|██████                              | 3/18 [00:00<00:01, 10.62it/s, v_num=19, train_loss_step=98.10, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  17%|██████                              | 3/18 [00:00<00:01, 10.62it/s, v_num=19, train_loss_step=65.10, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  22%|████████                            | 4/18 [00:00<00:01, 10.48it/s, v_num=19, train_loss_step=65.10, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  22%|████████                            | 4/18 [00:00<00:01, 10.48it/s, v_num=19, train_loss_step=73.60, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  28%|██████████                          | 5/18 [00:00<00:01, 10.85it/s, v_num=19, train_loss_step=73.60, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  28%|██████████                          | 5/18 [00:00<00:01, 10.85it/s, v_num=19, train_loss_step=75.60, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  33%|████████████                        | 6/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=75.60, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  33%|████████████                        | 6/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=59.00, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  39%|██████████████                      | 7/18 [00:00<00:01, 10.96it/s, v_num=19, train_loss_step=59.00, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  39%|██████████████                      | 7/18 [00:00<00:01, 10.96it/s, v_num=19, train_loss_step=74.70, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  44%|████████████████                    | 8/18 [00:00<00:00, 10.97it/s, v_num=19, train_loss_step=74.70, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  44%|████████████████                    | 8/18 [00:00<00:00, 10.97it/s, v_num=19, train_loss_step=95.30, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.90it/s, v_num=19, train_loss_step=95.30, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.87it/s, v_num=19, train_loss_step=98.10, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  56%|███████████████████▍               | 10/18 [00:00<00:00, 11.08it/s, v_num=19, train_loss_step=98.10, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  56%|███████████████████▍               | 10/18 [00:00<00:00, 11.08it/s, v_num=19, train_loss_step=133.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  61%|█████████████████████▍             | 11/18 [00:00<00:00, 11.02it/s, v_num=19, train_loss_step=133.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  61%|█████████████████████▍             | 11/18 [00:00<00:00, 11.02it/s, v_num=19, train_loss_step=98.00, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 11.12it/s, v_num=19, train_loss_step=98.00, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.96it/s, v_num=19, train_loss_step=79.60, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.90it/s, v_num=19, train_loss_step=79.60, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.88it/s, v_num=19, train_loss_step=68.80, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.72it/s, v_num=19, train_loss_step=68.80, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.70it/s, v_num=19, train_loss_step=119.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.74it/s, v_num=19, train_loss_step=119.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.74it/s, v_num=19, train_loss_step=100.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.59it/s, v_num=19, train_loss_step=100.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=196.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=196.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=136.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=136.0, val_loss=925.0, train_loss_epoch=94.30]

Epoch 10: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=65.90, val_loss=925.0, train_loss_epoch=94.30]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.70it/s]

Epoch 10: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.33it/s, v_num=19, train_loss_step=65.90, val_loss=919.0, train_loss_epoch=94.30]

Epoch 10: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.25it/s, v_num=19, train_loss_step=65.90, val_loss=919.0, train_loss_epoch=94.50]

Epoch 10:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=65.90, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=65.90, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:   6%|██                                  | 1/18 [00:00<00:01, 10.53it/s, v_num=19, train_loss_step=65.90, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:   6%|██                                  | 1/18 [00:00<00:01, 10.53it/s, v_num=19, train_loss_step=145.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  11%|████                                | 2/18 [00:00<00:01, 11.53it/s, v_num=19, train_loss_step=145.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  11%|████                                | 2/18 [00:00<00:01, 10.57it/s, v_num=19, train_loss_step=61.70, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  17%|██████                              | 3/18 [00:00<00:01, 10.42it/s, v_num=19, train_loss_step=61.70, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  17%|██████                              | 3/18 [00:00<00:01, 10.42it/s, v_num=19, train_loss_step=55.20, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  22%|████████                            | 4/18 [00:00<00:01, 10.27it/s, v_num=19, train_loss_step=55.20, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  22%|████████                            | 4/18 [00:00<00:01, 10.22it/s, v_num=19, train_loss_step=103.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  28%|██████████                          | 5/18 [00:00<00:01, 10.53it/s, v_num=19, train_loss_step=103.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  28%|██████████                          | 5/18 [00:00<00:01, 10.53it/s, v_num=19, train_loss_step=106.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  33%|████████████                        | 6/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=106.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  33%|████████████                        | 6/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=121.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  39%|██████████████                      | 7/18 [00:00<00:01, 10.08it/s, v_num=19, train_loss_step=121.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  39%|██████████████                      | 7/18 [00:00<00:01, 10.05it/s, v_num=19, train_loss_step=98.60, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  44%|████████████████                    | 8/18 [00:00<00:00, 10.11it/s, v_num=19, train_loss_step=98.60, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  44%|████████████████                    | 8/18 [00:00<00:00, 10.11it/s, v_num=19, train_loss_step=109.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.07it/s, v_num=19, train_loss_step=109.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.05it/s, v_num=19, train_loss_step=56.80, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.13it/s, v_num=19, train_loss_step=56.80, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.11it/s, v_num=19, train_loss_step=96.40, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.23it/s, v_num=19, train_loss_step=96.40, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.23it/s, v_num=19, train_loss_step=121.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.24it/s, v_num=19, train_loss_step=121.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.24it/s, v_num=19, train_loss_step=131.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=131.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=52.00, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.07it/s, v_num=19, train_loss_step=52.00, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.07it/s, v_num=19, train_loss_step=64.30, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.10it/s, v_num=19, train_loss_step=64.30, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.10it/s, v_num=19, train_loss_step=93.60, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.12it/s, v_num=19, train_loss_step=93.60, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.12it/s, v_num=19, train_loss_step=142.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=142.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=141.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.07it/s, v_num=19, train_loss_step=141.0, val_loss=919.0, train_loss_epoch=94.50]

Epoch 11: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.07it/s, v_num=19, train_loss_step=95.40, val_loss=919.0, train_loss_epoch=94.50]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.60it/s]

Epoch 11: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.80it/s, v_num=19, train_loss_step=95.40, val_loss=945.0, train_loss_epoch=94.50]

Epoch 11: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.79it/s, v_num=19, train_loss_step=95.40, val_loss=945.0, train_loss_epoch=99.60]

Epoch 11:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=95.40, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=95.40, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:   6%|██                                  | 1/18 [00:00<00:01,  9.83it/s, v_num=19, train_loss_step=95.40, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:   6%|██                                  | 1/18 [00:00<00:01,  9.83it/s, v_num=19, train_loss_step=35.30, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  11%|████                                | 2/18 [00:00<00:01, 10.18it/s, v_num=19, train_loss_step=35.30, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  11%|████                                | 2/18 [00:00<00:01, 10.18it/s, v_num=19, train_loss_step=79.90, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  17%|██████                              | 3/18 [00:00<00:01, 10.09it/s, v_num=19, train_loss_step=79.90, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  17%|██████                              | 3/18 [00:00<00:01, 10.03it/s, v_num=19, train_loss_step=69.30, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  22%|████████                            | 4/18 [00:00<00:01, 10.25it/s, v_num=19, train_loss_step=69.30, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  22%|████████                            | 4/18 [00:00<00:01, 10.20it/s, v_num=19, train_loss_step=117.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  28%|██████████                          | 5/18 [00:00<00:01, 10.43it/s, v_num=19, train_loss_step=117.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  28%|██████████                          | 5/18 [00:00<00:01, 10.43it/s, v_num=19, train_loss_step=170.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  33%|████████████                        | 6/18 [00:00<00:01, 10.35it/s, v_num=19, train_loss_step=170.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  33%|████████████                        | 6/18 [00:00<00:01, 10.35it/s, v_num=19, train_loss_step=115.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  39%|██████████████                      | 7/18 [00:00<00:01, 10.51it/s, v_num=19, train_loss_step=115.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  39%|██████████████                      | 7/18 [00:00<00:01, 10.48it/s, v_num=19, train_loss_step=75.00, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  44%|████████████████                    | 8/18 [00:00<00:00, 10.47it/s, v_num=19, train_loss_step=75.00, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  44%|████████████████                    | 8/18 [00:00<00:00, 10.47it/s, v_num=19, train_loss_step=149.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.51it/s, v_num=19, train_loss_step=149.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.51it/s, v_num=19, train_loss_step=67.10, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.49it/s, v_num=19, train_loss_step=67.10, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.49it/s, v_num=19, train_loss_step=63.70, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=63.70, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=110.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.47it/s, v_num=19, train_loss_step=110.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.47it/s, v_num=19, train_loss_step=82.60, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=82.60, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.48it/s, v_num=19, train_loss_step=73.00, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=73.00, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=115.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=115.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=116.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=116.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.59it/s, v_num=19, train_loss_step=137.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  94%|█████████████████████████████████  | 17/18 [00:01<00:00,  9.80it/s, v_num=19, train_loss_step=137.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12:  94%|█████████████████████████████████  | 17/18 [00:01<00:00,  9.80it/s, v_num=19, train_loss_step=114.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.80it/s, v_num=19, train_loss_step=114.0, val_loss=945.0, train_loss_epoch=99.60]

Epoch 12: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.79it/s, v_num=19, train_loss_step=105.0, val_loss=945.0, train_loss_epoch=99.60]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.38it/s]

Epoch 12: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.51it/s, v_num=19, train_loss_step=105.0, val_loss=977.0, train_loss_epoch=99.60]

Epoch 12: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.51it/s, v_num=19, train_loss_step=105.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 12:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=105.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=105.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:   6%|██                                  | 1/18 [00:00<00:01, 12.42it/s, v_num=19, train_loss_step=105.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:   6%|██                                  | 1/18 [00:00<00:01, 12.42it/s, v_num=19, train_loss_step=115.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  11%|████                                | 2/18 [00:00<00:01, 11.38it/s, v_num=19, train_loss_step=115.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  11%|████                                | 2/18 [00:00<00:01, 11.38it/s, v_num=19, train_loss_step=37.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  17%|██████                              | 3/18 [00:00<00:01, 11.15it/s, v_num=19, train_loss_step=37.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  17%|██████                              | 3/18 [00:00<00:01, 11.08it/s, v_num=19, train_loss_step=85.40, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  22%|████████                            | 4/18 [00:00<00:01, 10.95it/s, v_num=19, train_loss_step=85.40, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  22%|████████                            | 4/18 [00:00<00:01, 10.95it/s, v_num=19, train_loss_step=89.60, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  28%|██████████                          | 5/18 [00:00<00:01, 10.86it/s, v_num=19, train_loss_step=89.60, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  28%|██████████                          | 5/18 [00:00<00:01, 10.86it/s, v_num=19, train_loss_step=74.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  33%|████████████                        | 6/18 [00:00<00:01, 10.50it/s, v_num=19, train_loss_step=74.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  33%|████████████                        | 6/18 [00:00<00:01, 10.47it/s, v_num=19, train_loss_step=94.60, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  39%|██████████████                      | 7/18 [00:00<00:01, 10.77it/s, v_num=19, train_loss_step=94.60, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  39%|██████████████                      | 7/18 [00:00<00:01, 10.77it/s, v_num=19, train_loss_step=80.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  44%|████████████████                    | 8/18 [00:00<00:00, 10.69it/s, v_num=19, train_loss_step=80.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  44%|████████████████                    | 8/18 [00:00<00:00, 10.69it/s, v_num=19, train_loss_step=62.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.57it/s, v_num=19, train_loss_step=62.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.57it/s, v_num=19, train_loss_step=121.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.68it/s, v_num=19, train_loss_step=121.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.65it/s, v_num=19, train_loss_step=94.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.88it/s, v_num=19, train_loss_step=94.20, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.71it/s, v_num=19, train_loss_step=85.70, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.71it/s, v_num=19, train_loss_step=85.70, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.70it/s, v_num=19, train_loss_step=89.10, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.68it/s, v_num=19, train_loss_step=89.10, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=72.60, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=72.60, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=64.00, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.57it/s, v_num=19, train_loss_step=64.00, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.56it/s, v_num=19, train_loss_step=184.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=184.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=99.30, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.77it/s, v_num=19, train_loss_step=99.30, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=118.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.76it/s, v_num=19, train_loss_step=118.0, val_loss=977.0, train_loss_epoch=99.70]

Epoch 13: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.76it/s, v_num=19, train_loss_step=108.0, val_loss=977.0, train_loss_epoch=99.70]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.33it/s]

Epoch 13: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.37it/s, v_num=19, train_loss_step=108.0, val_loss=962.0, train_loss_epoch=99.70]

Epoch 13: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.37it/s, v_num=19, train_loss_step=108.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 13:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=108.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=108.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:   6%|██                                  | 1/18 [00:00<00:01, 10.08it/s, v_num=19, train_loss_step=108.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:   6%|██                                  | 1/18 [00:00<00:01, 10.08it/s, v_num=19, train_loss_step=88.60, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  11%|████                                | 2/18 [00:00<00:01, 11.22it/s, v_num=19, train_loss_step=88.60, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  11%|████                                | 2/18 [00:00<00:01, 11.22it/s, v_num=19, train_loss_step=41.30, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  17%|██████                              | 3/18 [00:00<00:01, 10.69it/s, v_num=19, train_loss_step=41.30, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  17%|██████                              | 3/18 [00:00<00:01, 10.69it/s, v_num=19, train_loss_step=115.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  22%|████████                            | 4/18 [00:00<00:01, 10.94it/s, v_num=19, train_loss_step=115.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  22%|████████                            | 4/18 [00:00<00:01, 10.88it/s, v_num=19, train_loss_step=63.30, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  28%|██████████                          | 5/18 [00:00<00:01, 10.59it/s, v_num=19, train_loss_step=63.30, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  28%|██████████                          | 5/18 [00:00<00:01, 10.59it/s, v_num=19, train_loss_step=87.60, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  33%|████████████                        | 6/18 [00:00<00:01, 10.72it/s, v_num=19, train_loss_step=87.60, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  33%|████████████                        | 6/18 [00:00<00:01, 10.72it/s, v_num=19, train_loss_step=86.60, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  39%|██████████████                      | 7/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=86.60, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  39%|██████████████                      | 7/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=133.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  44%|████████████████                    | 8/18 [00:00<00:00, 10.68it/s, v_num=19, train_loss_step=133.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  44%|████████████████                    | 8/18 [00:00<00:00, 10.68it/s, v_num=19, train_loss_step=88.10, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.74it/s, v_num=19, train_loss_step=88.10, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.71it/s, v_num=19, train_loss_step=55.90, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.76it/s, v_num=19, train_loss_step=55.90, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.76it/s, v_num=19, train_loss_step=155.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.85it/s, v_num=19, train_loss_step=155.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.85it/s, v_num=19, train_loss_step=65.10, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.82it/s, v_num=19, train_loss_step=65.10, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.82it/s, v_num=19, train_loss_step=77.10, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.80it/s, v_num=19, train_loss_step=77.10, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.80it/s, v_num=19, train_loss_step=65.40, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.91it/s, v_num=19, train_loss_step=65.40, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.91it/s, v_num=19, train_loss_step=111.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.75it/s, v_num=19, train_loss_step=111.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.75it/s, v_num=19, train_loss_step=101.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.70it/s, v_num=19, train_loss_step=101.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.70it/s, v_num=19, train_loss_step=123.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.75it/s, v_num=19, train_loss_step=123.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.74it/s, v_num=19, train_loss_step=121.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.83it/s, v_num=19, train_loss_step=121.0, val_loss=962.0, train_loss_epoch=92.90]

Epoch 14: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.83it/s, v_num=19, train_loss_step=96.10, val_loss=962.0, train_loss_epoch=92.90]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 42.07it/s]

Epoch 14: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.42it/s, v_num=19, train_loss_step=96.10, val_loss=972.0, train_loss_epoch=92.90]

Epoch 14: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.41it/s, v_num=19, train_loss_step=96.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 14:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=96.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=96.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:   6%|██                                  | 1/18 [00:00<00:01,  9.50it/s, v_num=19, train_loss_step=96.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:   6%|██                                  | 1/18 [00:00<00:01,  9.50it/s, v_num=19, train_loss_step=104.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  11%|████                                | 2/18 [00:00<00:01, 10.75it/s, v_num=19, train_loss_step=104.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  11%|████                                | 2/18 [00:00<00:01, 10.75it/s, v_num=19, train_loss_step=77.70, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  17%|██████                              | 3/18 [00:00<00:01, 10.60it/s, v_num=19, train_loss_step=77.70, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  17%|██████                              | 3/18 [00:00<00:01, 10.60it/s, v_num=19, train_loss_step=92.70, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  22%|████████                            | 4/18 [00:00<00:01, 10.65it/s, v_num=19, train_loss_step=92.70, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  22%|████████                            | 4/18 [00:00<00:01, 10.65it/s, v_num=19, train_loss_step=122.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  28%|██████████                          | 5/18 [00:00<00:01, 10.63it/s, v_num=19, train_loss_step=122.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  28%|██████████                          | 5/18 [00:00<00:01, 10.63it/s, v_num=19, train_loss_step=95.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  33%|████████████                        | 6/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=95.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  33%|████████████                        | 6/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=97.40, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  39%|██████████████                      | 7/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=97.40, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  39%|██████████████                      | 7/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=70.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  44%|████████████████                    | 8/18 [00:00<00:00, 10.83it/s, v_num=19, train_loss_step=70.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  44%|████████████████                    | 8/18 [00:00<00:00, 10.60it/s, v_num=19, train_loss_step=93.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.72it/s, v_num=19, train_loss_step=93.10, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.70it/s, v_num=19, train_loss_step=177.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.73it/s, v_num=19, train_loss_step=177.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.71it/s, v_num=19, train_loss_step=94.90, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.93it/s, v_num=19, train_loss_step=94.90, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.93it/s, v_num=19, train_loss_step=83.50, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.90it/s, v_num=19, train_loss_step=83.50, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.90it/s, v_num=19, train_loss_step=93.20, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.87it/s, v_num=19, train_loss_step=93.20, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.87it/s, v_num=19, train_loss_step=103.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.84it/s, v_num=19, train_loss_step=103.0, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.84it/s, v_num=19, train_loss_step=47.60, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.95it/s, v_num=19, train_loss_step=47.60, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.95it/s, v_num=19, train_loss_step=91.40, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.87it/s, v_num=19, train_loss_step=91.40, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.87it/s, v_num=19, train_loss_step=46.80, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 11.01it/s, v_num=19, train_loss_step=46.80, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 11.01it/s, v_num=19, train_loss_step=64.80, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.98it/s, v_num=19, train_loss_step=64.80, val_loss=972.0, train_loss_epoch=93.00]

Epoch 15: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.88it/s, v_num=19, train_loss_step=80.70, val_loss=972.0, train_loss_epoch=93.00]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.93it/s]

Epoch 15: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=80.70, val_loss=956.0, train_loss_epoch=93.00]

Epoch 15: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=80.70, val_loss=956.0, train_loss_epoch=90.90]

Epoch 15:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=80.70, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=80.70, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:   6%|██                                  | 1/18 [00:00<00:01,  9.49it/s, v_num=19, train_loss_step=80.70, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:   6%|██                                  | 1/18 [00:00<00:01,  9.49it/s, v_num=19, train_loss_step=96.50, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  11%|████                                | 2/18 [00:00<00:01, 10.49it/s, v_num=19, train_loss_step=96.50, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  11%|████                                | 2/18 [00:00<00:01, 10.49it/s, v_num=19, train_loss_step=73.60, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  17%|██████                              | 3/18 [00:00<00:01, 11.10it/s, v_num=19, train_loss_step=73.60, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  17%|██████                              | 3/18 [00:00<00:01, 11.10it/s, v_num=19, train_loss_step=131.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  22%|████████                            | 4/18 [00:00<00:01, 10.87it/s, v_num=19, train_loss_step=131.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  22%|████████                            | 4/18 [00:00<00:01, 10.81it/s, v_num=19, train_loss_step=110.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  28%|██████████                          | 5/18 [00:00<00:01, 10.73it/s, v_num=19, train_loss_step=110.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  28%|██████████                          | 5/18 [00:00<00:01, 10.69it/s, v_num=19, train_loss_step=139.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  33%|████████████                        | 6/18 [00:00<00:01, 10.87it/s, v_num=19, train_loss_step=139.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  33%|████████████                        | 6/18 [00:00<00:01, 10.87it/s, v_num=19, train_loss_step=94.50, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  39%|██████████████                      | 7/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=94.50, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  39%|██████████████                      | 7/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=106.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  44%|████████████████                    | 8/18 [00:00<00:00, 10.80it/s, v_num=19, train_loss_step=106.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  44%|████████████████                    | 8/18 [00:00<00:00, 10.80it/s, v_num=19, train_loss_step=62.40, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.57it/s, v_num=19, train_loss_step=62.40, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.55it/s, v_num=19, train_loss_step=83.20, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.57it/s, v_num=19, train_loss_step=83.20, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.57it/s, v_num=19, train_loss_step=126.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=126.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=67.50, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.43it/s, v_num=19, train_loss_step=67.50, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.41it/s, v_num=19, train_loss_step=107.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.47it/s, v_num=19, train_loss_step=107.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.47it/s, v_num=19, train_loss_step=151.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=151.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=40.90, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=40.90, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.56it/s, v_num=19, train_loss_step=82.20, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.67it/s, v_num=19, train_loss_step=82.20, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.67it/s, v_num=19, train_loss_step=107.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.67it/s, v_num=19, train_loss_step=107.0, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.67it/s, v_num=19, train_loss_step=53.70, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=53.70, val_loss=956.0, train_loss_epoch=90.90]

Epoch 16: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=60.70, val_loss=956.0, train_loss_epoch=90.90]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.58it/s]

Epoch 16: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.37it/s, v_num=19, train_loss_step=60.70, val_loss=943.0, train_loss_epoch=90.90]

Epoch 16: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.37it/s, v_num=19, train_loss_step=60.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 16:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=60.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=60.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:   6%|██                                  | 1/18 [00:00<00:01,  9.97it/s, v_num=19, train_loss_step=60.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:   6%|██                                  | 1/18 [00:00<00:01,  9.97it/s, v_num=19, train_loss_step=61.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  11%|████                                | 2/18 [00:00<00:01,  9.95it/s, v_num=19, train_loss_step=61.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  11%|████                                | 2/18 [00:00<00:01,  9.95it/s, v_num=19, train_loss_step=104.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  17%|██████                              | 3/18 [00:00<00:01, 10.28it/s, v_num=19, train_loss_step=104.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  17%|██████                              | 3/18 [00:00<00:01, 10.28it/s, v_num=19, train_loss_step=107.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  22%|████████                            | 4/18 [00:00<00:01, 10.28it/s, v_num=19, train_loss_step=107.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  22%|████████                            | 4/18 [00:00<00:01, 10.28it/s, v_num=19, train_loss_step=123.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  28%|██████████                          | 5/18 [00:00<00:01, 10.24it/s, v_num=19, train_loss_step=123.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  28%|██████████                          | 5/18 [00:00<00:01, 10.20it/s, v_num=19, train_loss_step=81.80, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  33%|████████████                        | 6/18 [00:00<00:01,  9.95it/s, v_num=19, train_loss_step=81.80, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  33%|████████████                        | 6/18 [00:00<00:01,  9.92it/s, v_num=19, train_loss_step=50.10, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  39%|██████████████                      | 7/18 [00:00<00:01, 10.27it/s, v_num=19, train_loss_step=50.10, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  39%|██████████████                      | 7/18 [00:00<00:01, 10.04it/s, v_num=19, train_loss_step=77.10, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  44%|████████████████                    | 8/18 [00:00<00:01,  9.59it/s, v_num=19, train_loss_step=77.10, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  44%|████████████████                    | 8/18 [00:00<00:01,  9.59it/s, v_num=19, train_loss_step=73.90, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  50%|██████████████████                  | 9/18 [00:00<00:00,  9.53it/s, v_num=19, train_loss_step=73.90, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  50%|██████████████████                  | 9/18 [00:00<00:00,  9.53it/s, v_num=19, train_loss_step=126.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.66it/s, v_num=19, train_loss_step=126.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.64it/s, v_num=19, train_loss_step=79.20, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.72it/s, v_num=19, train_loss_step=79.20, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.72it/s, v_num=19, train_loss_step=122.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  67%|███████████████████████▎           | 12/18 [00:01<00:00,  9.80it/s, v_num=19, train_loss_step=122.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  67%|███████████████████████▎           | 12/18 [00:01<00:00,  9.78it/s, v_num=19, train_loss_step=99.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  72%|█████████████████████████▎         | 13/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=99.70, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  72%|█████████████████████████▎         | 13/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=53.50, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  78%|███████████████████████████▏       | 14/18 [00:01<00:00,  9.83it/s, v_num=19, train_loss_step=53.50, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  78%|███████████████████████████▏       | 14/18 [00:01<00:00,  9.83it/s, v_num=19, train_loss_step=131.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=131.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=72.20, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  89%|███████████████████████████████    | 16/18 [00:01<00:00,  9.96it/s, v_num=19, train_loss_step=72.20, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  89%|███████████████████████████████    | 16/18 [00:01<00:00,  9.96it/s, v_num=19, train_loss_step=102.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.04it/s, v_num=19, train_loss_step=102.0, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.04it/s, v_num=19, train_loss_step=79.40, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.16it/s, v_num=19, train_loss_step=79.40, val_loss=943.0, train_loss_epoch=94.00]

Epoch 17: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.07it/s, v_num=19, train_loss_step=95.10, val_loss=943.0, train_loss_epoch=94.00]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.91it/s]

Epoch 17: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.80it/s, v_num=19, train_loss_step=95.10, val_loss=959.0, train_loss_epoch=94.00]

Epoch 17: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.76it/s, v_num=19, train_loss_step=95.10, val_loss=959.0, train_loss_epoch=91.00]

Epoch 17:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=95.10, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=95.10, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:   6%|██                                  | 1/18 [00:00<00:01, 10.54it/s, v_num=19, train_loss_step=95.10, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:   6%|██                                  | 1/18 [00:00<00:01, 10.54it/s, v_num=19, train_loss_step=68.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  11%|████                                | 2/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=68.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  11%|████                                | 2/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=117.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  17%|██████                              | 3/18 [00:00<00:01, 10.05it/s, v_num=19, train_loss_step=117.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  17%|██████                              | 3/18 [00:00<00:01, 10.05it/s, v_num=19, train_loss_step=98.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  22%|████████                            | 4/18 [00:00<00:01, 10.25it/s, v_num=19, train_loss_step=98.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  22%|████████                            | 4/18 [00:00<00:01, 10.20it/s, v_num=19, train_loss_step=66.50, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  28%|██████████                          | 5/18 [00:00<00:01, 10.14it/s, v_num=19, train_loss_step=66.50, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  28%|██████████                          | 5/18 [00:00<00:01, 10.14it/s, v_num=19, train_loss_step=110.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  33%|████████████                        | 6/18 [00:00<00:01, 10.27it/s, v_num=19, train_loss_step=110.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  33%|████████████                        | 6/18 [00:00<00:01, 10.27it/s, v_num=19, train_loss_step=42.30, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  39%|██████████████                      | 7/18 [00:00<00:01,  9.91it/s, v_num=19, train_loss_step=42.30, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  39%|██████████████                      | 7/18 [00:00<00:01,  9.91it/s, v_num=19, train_loss_step=76.00, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  44%|████████████████                    | 8/18 [00:00<00:01,  9.82it/s, v_num=19, train_loss_step=76.00, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  44%|████████████████                    | 8/18 [00:00<00:01,  9.79it/s, v_num=19, train_loss_step=85.70, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  50%|██████████████████                  | 9/18 [00:00<00:00,  9.71it/s, v_num=19, train_loss_step=85.70, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  50%|██████████████████                  | 9/18 [00:00<00:00,  9.71it/s, v_num=19, train_loss_step=54.30, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.89it/s, v_num=19, train_loss_step=54.30, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.89it/s, v_num=19, train_loss_step=96.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.93it/s, v_num=19, train_loss_step=96.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.93it/s, v_num=19, train_loss_step=90.50, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  67%|███████████████████████▎           | 12/18 [00:01<00:00,  9.98it/s, v_num=19, train_loss_step=90.50, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  67%|███████████████████████▎           | 12/18 [00:01<00:00,  9.98it/s, v_num=19, train_loss_step=115.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  72%|█████████████████████████▎         | 13/18 [00:01<00:00,  9.97it/s, v_num=19, train_loss_step=115.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  72%|█████████████████████████▎         | 13/18 [00:01<00:00,  9.97it/s, v_num=19, train_loss_step=67.60, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  78%|███████████████████████████▏       | 14/18 [00:01<00:00,  9.98it/s, v_num=19, train_loss_step=67.60, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  78%|███████████████████████████▏       | 14/18 [00:01<00:00,  9.98it/s, v_num=19, train_loss_step=201.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.08it/s, v_num=19, train_loss_step=201.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.06it/s, v_num=19, train_loss_step=101.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.02it/s, v_num=19, train_loss_step=101.0, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.02it/s, v_num=19, train_loss_step=59.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.08it/s, v_num=19, train_loss_step=59.40, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.08it/s, v_num=19, train_loss_step=45.20, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.13it/s, v_num=19, train_loss_step=45.20, val_loss=959.0, train_loss_epoch=91.00]

Epoch 18: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.12it/s, v_num=19, train_loss_step=81.40, val_loss=959.0, train_loss_epoch=91.00]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.75it/s]

Epoch 18: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.81it/s, v_num=19, train_loss_step=81.40, val_loss=942.0, train_loss_epoch=91.00]

Epoch 18: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.80it/s, v_num=19, train_loss_step=81.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 18:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=81.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=81.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:   6%|██                                  | 1/18 [00:00<00:01,  9.68it/s, v_num=19, train_loss_step=81.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:   6%|██                                  | 1/18 [00:00<00:01,  9.68it/s, v_num=19, train_loss_step=106.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  11%|████                                | 2/18 [00:00<00:01, 10.50it/s, v_num=19, train_loss_step=106.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  11%|████                                | 2/18 [00:00<00:01, 10.50it/s, v_num=19, train_loss_step=91.90, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  17%|██████                              | 3/18 [00:00<00:01, 10.45it/s, v_num=19, train_loss_step=91.90, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  17%|██████                              | 3/18 [00:00<00:01, 10.45it/s, v_num=19, train_loss_step=88.50, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  22%|████████                            | 4/18 [00:00<00:01, 10.10it/s, v_num=19, train_loss_step=88.50, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  22%|████████                            | 4/18 [00:00<00:01, 10.10it/s, v_num=19, train_loss_step=80.60, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  28%|██████████                          | 5/18 [00:00<00:01,  9.96it/s, v_num=19, train_loss_step=80.60, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  28%|██████████                          | 5/18 [00:00<00:01,  9.96it/s, v_num=19, train_loss_step=100.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  33%|████████████                        | 6/18 [00:00<00:01, 10.25it/s, v_num=19, train_loss_step=100.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  33%|████████████                        | 6/18 [00:00<00:01, 10.25it/s, v_num=19, train_loss_step=113.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  39%|██████████████                      | 7/18 [00:00<00:01, 10.26it/s, v_num=19, train_loss_step=113.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  39%|██████████████                      | 7/18 [00:00<00:01, 10.23it/s, v_num=19, train_loss_step=148.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  44%|████████████████                    | 8/18 [00:00<00:00, 10.32it/s, v_num=19, train_loss_step=148.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  44%|████████████████                    | 8/18 [00:00<00:00, 10.32it/s, v_num=19, train_loss_step=51.80, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.35it/s, v_num=19, train_loss_step=51.80, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.35it/s, v_num=19, train_loss_step=85.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.42it/s, v_num=19, train_loss_step=85.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.40it/s, v_num=19, train_loss_step=82.50, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=82.50, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=60.20, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.53it/s, v_num=19, train_loss_step=60.20, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=95.20, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.65it/s, v_num=19, train_loss_step=95.20, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.65it/s, v_num=19, train_loss_step=152.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.68it/s, v_num=19, train_loss_step=152.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.68it/s, v_num=19, train_loss_step=88.10, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.67it/s, v_num=19, train_loss_step=88.10, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.65it/s, v_num=19, train_loss_step=40.90, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=40.90, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=39.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=39.40, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=120.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=120.0, val_loss=942.0, train_loss_epoch=87.60]

Epoch 19: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=109.0, val_loss=942.0, train_loss_epoch=87.60]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.84it/s]

Epoch 19: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.28it/s, v_num=19, train_loss_step=109.0, val_loss=944.0, train_loss_epoch=87.60]

Epoch 19: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.26it/s, v_num=19, train_loss_step=109.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 19:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=109.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=109.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:   6%|██                                  | 1/18 [00:00<00:01, 11.26it/s, v_num=19, train_loss_step=109.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:   6%|██                                  | 1/18 [00:00<00:01, 11.26it/s, v_num=19, train_loss_step=139.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  11%|████                                | 2/18 [00:00<00:01, 11.03it/s, v_num=19, train_loss_step=139.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  11%|████                                | 2/18 [00:00<00:01, 10.93it/s, v_num=19, train_loss_step=79.80, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  17%|██████                              | 3/18 [00:00<00:01, 11.02it/s, v_num=19, train_loss_step=79.80, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  17%|██████                              | 3/18 [00:00<00:01, 11.02it/s, v_num=19, train_loss_step=70.60, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  22%|████████                            | 4/18 [00:00<00:01, 11.21it/s, v_num=19, train_loss_step=70.60, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  22%|████████                            | 4/18 [00:00<00:01, 11.21it/s, v_num=19, train_loss_step=61.40, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  28%|██████████                          | 5/18 [00:00<00:01, 11.08it/s, v_num=19, train_loss_step=61.40, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  28%|██████████                          | 5/18 [00:00<00:01, 11.08it/s, v_num=19, train_loss_step=85.10, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  33%|████████████                        | 6/18 [00:00<00:01, 10.99it/s, v_num=19, train_loss_step=85.10, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  33%|████████████                        | 6/18 [00:00<00:01, 10.99it/s, v_num=19, train_loss_step=64.50, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  39%|██████████████                      | 7/18 [00:00<00:00, 11.20it/s, v_num=19, train_loss_step=64.50, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  39%|██████████████                      | 7/18 [00:00<00:00, 11.20it/s, v_num=19, train_loss_step=111.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  44%|████████████████                    | 8/18 [00:00<00:00, 10.75it/s, v_num=19, train_loss_step=111.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  44%|████████████████                    | 8/18 [00:00<00:00, 10.73it/s, v_num=19, train_loss_step=146.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.68it/s, v_num=19, train_loss_step=146.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.68it/s, v_num=19, train_loss_step=93.80, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.81it/s, v_num=19, train_loss_step=93.80, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.81it/s, v_num=19, train_loss_step=93.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.69it/s, v_num=19, train_loss_step=93.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.69it/s, v_num=19, train_loss_step=91.20, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=91.20, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=90.20, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=90.20, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=53.80, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=53.80, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.62it/s, v_num=19, train_loss_step=65.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=65.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=90.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=90.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=106.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.66it/s, v_num=19, train_loss_step=106.0, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.65it/s, v_num=19, train_loss_step=92.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=92.30, val_loss=944.0, train_loss_epoch=91.80]

Epoch 20: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.56it/s, v_num=19, train_loss_step=89.10, val_loss=944.0, train_loss_epoch=91.80]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 53.28it/s]

Epoch 20: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.31it/s, v_num=19, train_loss_step=89.10, val_loss=960.0, train_loss_epoch=91.80]

Epoch 20: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.24it/s, v_num=19, train_loss_step=89.10, val_loss=960.0, train_loss_epoch=90.10]

Epoch 20:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=89.10, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=89.10, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:   6%|██                                  | 1/18 [00:00<00:01,  9.07it/s, v_num=19, train_loss_step=89.10, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:   6%|██                                  | 1/18 [00:00<00:01,  8.91it/s, v_num=19, train_loss_step=74.80, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  11%|████                                | 2/18 [00:00<00:01,  9.40it/s, v_num=19, train_loss_step=74.80, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  11%|████                                | 2/18 [00:00<00:01,  9.40it/s, v_num=19, train_loss_step=112.0, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  17%|██████                              | 3/18 [00:00<00:01,  9.33it/s, v_num=19, train_loss_step=112.0, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  17%|██████                              | 3/18 [00:00<00:01,  9.27it/s, v_num=19, train_loss_step=75.40, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  22%|████████                            | 4/18 [00:00<00:01,  9.39it/s, v_num=19, train_loss_step=75.40, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  22%|████████                            | 4/18 [00:00<00:01,  9.39it/s, v_num=19, train_loss_step=58.40, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  28%|██████████                          | 5/18 [00:00<00:01,  9.91it/s, v_num=19, train_loss_step=58.40, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  28%|██████████                          | 5/18 [00:00<00:01,  9.91it/s, v_num=19, train_loss_step=144.0, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  33%|████████████                        | 6/18 [00:00<00:01,  9.80it/s, v_num=19, train_loss_step=144.0, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  33%|████████████                        | 6/18 [00:00<00:01,  9.80it/s, v_num=19, train_loss_step=84.40, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  39%|██████████████                      | 7/18 [00:00<00:01,  9.84it/s, v_num=19, train_loss_step=84.40, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  39%|██████████████                      | 7/18 [00:00<00:01,  9.84it/s, v_num=19, train_loss_step=56.90, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  44%|████████████████                    | 8/18 [00:00<00:01,  9.85it/s, v_num=19, train_loss_step=56.90, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  44%|████████████████                    | 8/18 [00:00<00:01,  9.82it/s, v_num=19, train_loss_step=87.80, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.00it/s, v_num=19, train_loss_step=87.80, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.00it/s, v_num=19, train_loss_step=78.90, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.99it/s, v_num=19, train_loss_step=78.90, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.99it/s, v_num=19, train_loss_step=139.0, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.92it/s, v_num=19, train_loss_step=139.0, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=85.80, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.02it/s, v_num=19, train_loss_step=85.80, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.02it/s, v_num=19, train_loss_step=60.20, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.18it/s, v_num=19, train_loss_step=60.20, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.18it/s, v_num=19, train_loss_step=96.60, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.21it/s, v_num=19, train_loss_step=96.60, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.21it/s, v_num=19, train_loss_step=80.20, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.23it/s, v_num=19, train_loss_step=80.20, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.23it/s, v_num=19, train_loss_step=74.30, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.11it/s, v_num=19, train_loss_step=74.30, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.11it/s, v_num=19, train_loss_step=70.60, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.18it/s, v_num=19, train_loss_step=70.60, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.17it/s, v_num=19, train_loss_step=91.50, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.18it/s, v_num=19, train_loss_step=91.50, val_loss=960.0, train_loss_epoch=90.10]

Epoch 21: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.18it/s, v_num=19, train_loss_step=95.10, val_loss=960.0, train_loss_epoch=90.10]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.91it/s]

Epoch 21: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.84it/s, v_num=19, train_loss_step=95.10, val_loss=969.0, train_loss_epoch=90.10]

Epoch 21: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.84it/s, v_num=19, train_loss_step=95.10, val_loss=969.0, train_loss_epoch=87.00]

Epoch 21:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=95.10, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=95.10, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:   6%|██                                  | 1/18 [00:00<00:01, 11.00it/s, v_num=19, train_loss_step=95.10, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:   6%|██                                  | 1/18 [00:00<00:01, 11.00it/s, v_num=19, train_loss_step=68.30, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  11%|████                                | 2/18 [00:00<00:01, 11.00it/s, v_num=19, train_loss_step=68.30, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  11%|████                                | 2/18 [00:00<00:01, 10.90it/s, v_num=19, train_loss_step=119.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  17%|██████                              | 3/18 [00:00<00:01, 10.84it/s, v_num=19, train_loss_step=119.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  17%|██████                              | 3/18 [00:00<00:01, 10.77it/s, v_num=19, train_loss_step=62.80, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  22%|████████                            | 4/18 [00:00<00:01, 10.88it/s, v_num=19, train_loss_step=62.80, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  22%|████████                            | 4/18 [00:00<00:01, 10.88it/s, v_num=19, train_loss_step=117.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  28%|██████████                          | 5/18 [00:00<00:01, 11.04it/s, v_num=19, train_loss_step=117.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  28%|██████████                          | 5/18 [00:00<00:01, 11.04it/s, v_num=19, train_loss_step=65.40, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  33%|████████████                        | 6/18 [00:00<00:01, 10.96it/s, v_num=19, train_loss_step=65.40, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  33%|████████████                        | 6/18 [00:00<00:01, 10.65it/s, v_num=19, train_loss_step=81.60, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  39%|██████████████                      | 7/18 [00:00<00:01, 10.39it/s, v_num=19, train_loss_step=81.60, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  39%|██████████████                      | 7/18 [00:00<00:01, 10.39it/s, v_num=19, train_loss_step=91.50, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  44%|████████████████                    | 8/18 [00:00<00:00, 10.20it/s, v_num=19, train_loss_step=91.50, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  44%|████████████████                    | 8/18 [00:00<00:00, 10.17it/s, v_num=19, train_loss_step=94.20, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.24it/s, v_num=19, train_loss_step=94.20, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.24it/s, v_num=19, train_loss_step=46.90, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.23it/s, v_num=19, train_loss_step=46.90, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.21it/s, v_num=19, train_loss_step=120.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.28it/s, v_num=19, train_loss_step=120.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.28it/s, v_num=19, train_loss_step=43.20, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.31it/s, v_num=19, train_loss_step=43.20, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.31it/s, v_num=19, train_loss_step=99.60, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.36it/s, v_num=19, train_loss_step=99.60, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=110.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.26it/s, v_num=19, train_loss_step=110.0, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.26it/s, v_num=19, train_loss_step=92.40, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.31it/s, v_num=19, train_loss_step=92.40, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.31it/s, v_num=19, train_loss_step=94.70, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.31it/s, v_num=19, train_loss_step=94.70, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.31it/s, v_num=19, train_loss_step=64.00, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.30it/s, v_num=19, train_loss_step=64.00, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.29it/s, v_num=19, train_loss_step=82.90, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.24it/s, v_num=19, train_loss_step=82.90, val_loss=969.0, train_loss_epoch=87.00]

Epoch 22: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.24it/s, v_num=19, train_loss_step=129.0, val_loss=969.0, train_loss_epoch=87.00]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.82it/s]

Epoch 22: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.86it/s, v_num=19, train_loss_step=129.0, val_loss=974.0, train_loss_epoch=87.00]

Epoch 22: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.85it/s, v_num=19, train_loss_step=129.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 22:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=129.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=129.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:   6%|██                                  | 1/18 [00:00<00:01,  9.82it/s, v_num=19, train_loss_step=129.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:   6%|██                                  | 1/18 [00:00<00:01,  9.82it/s, v_num=19, train_loss_step=116.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  11%|████                                | 2/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=116.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  11%|████                                | 2/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=93.00, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  17%|██████                              | 3/18 [00:00<00:01, 11.39it/s, v_num=19, train_loss_step=93.00, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  17%|██████                              | 3/18 [00:00<00:01, 11.39it/s, v_num=19, train_loss_step=109.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  22%|████████                            | 4/18 [00:00<00:01, 10.92it/s, v_num=19, train_loss_step=109.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  22%|████████                            | 4/18 [00:00<00:01, 10.86it/s, v_num=19, train_loss_step=54.70, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  28%|██████████                          | 5/18 [00:00<00:01, 10.71it/s, v_num=19, train_loss_step=54.70, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  28%|██████████                          | 5/18 [00:00<00:01, 10.67it/s, v_num=19, train_loss_step=66.80, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  33%|████████████                        | 6/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=66.80, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  33%|████████████                        | 6/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=53.90, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  39%|██████████████                      | 7/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=53.90, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  39%|██████████████                      | 7/18 [00:00<00:01, 10.52it/s, v_num=19, train_loss_step=99.90, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  44%|████████████████                    | 8/18 [00:00<00:00, 10.46it/s, v_num=19, train_loss_step=99.90, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  44%|████████████████                    | 8/18 [00:00<00:00, 10.42it/s, v_num=19, train_loss_step=77.80, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.57it/s, v_num=19, train_loss_step=77.80, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.55it/s, v_num=19, train_loss_step=75.50, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.63it/s, v_num=19, train_loss_step=75.50, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.63it/s, v_num=19, train_loss_step=66.10, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.54it/s, v_num=19, train_loss_step=66.10, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.54it/s, v_num=19, train_loss_step=46.70, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.53it/s, v_num=19, train_loss_step=46.70, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.53it/s, v_num=19, train_loss_step=92.20, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=92.20, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=115.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.44it/s, v_num=19, train_loss_step=115.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.44it/s, v_num=19, train_loss_step=57.40, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=57.40, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=140.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=140.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=109.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=109.0, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=83.80, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.59it/s, v_num=19, train_loss_step=83.80, val_loss=974.0, train_loss_epoch=87.90]

Epoch 23: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.49it/s, v_num=19, train_loss_step=100.0, val_loss=974.0, train_loss_epoch=87.90]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 50.50it/s]

Epoch 23: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.21it/s, v_num=19, train_loss_step=100.0, val_loss=982.0, train_loss_epoch=87.90]

Epoch 23: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.11it/s, v_num=19, train_loss_step=100.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 23:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=100.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=100.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:   6%|██                                  | 1/18 [00:00<00:01, 11.52it/s, v_num=19, train_loss_step=100.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:   6%|██                                  | 1/18 [00:00<00:01, 11.52it/s, v_num=19, train_loss_step=63.70, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  11%|████                                | 2/18 [00:00<00:01, 11.25it/s, v_num=19, train_loss_step=63.70, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  11%|████                                | 2/18 [00:00<00:01, 11.25it/s, v_num=19, train_loss_step=89.30, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  17%|██████                              | 3/18 [00:00<00:01, 10.97it/s, v_num=19, train_loss_step=89.30, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  17%|██████                              | 3/18 [00:00<00:01, 10.97it/s, v_num=19, train_loss_step=47.00, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  22%|████████                            | 4/18 [00:00<00:01, 10.69it/s, v_num=19, train_loss_step=47.00, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  22%|████████                            | 4/18 [00:00<00:01, 10.69it/s, v_num=19, train_loss_step=74.80, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  28%|██████████                          | 5/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=74.80, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  28%|██████████                          | 5/18 [00:00<00:01, 10.76it/s, v_num=19, train_loss_step=77.10, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  33%|████████████                        | 6/18 [00:00<00:01, 10.71it/s, v_num=19, train_loss_step=77.10, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  33%|████████████                        | 6/18 [00:00<00:01, 10.71it/s, v_num=19, train_loss_step=140.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  39%|██████████████                      | 7/18 [00:00<00:01, 10.74it/s, v_num=19, train_loss_step=140.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  39%|██████████████                      | 7/18 [00:00<00:01, 10.74it/s, v_num=19, train_loss_step=137.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  44%|████████████████                    | 8/18 [00:00<00:00, 10.72it/s, v_num=19, train_loss_step=137.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  44%|████████████████                    | 8/18 [00:00<00:00, 10.72it/s, v_num=19, train_loss_step=76.40, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.64it/s, v_num=19, train_loss_step=76.40, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.64it/s, v_num=19, train_loss_step=57.80, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.52it/s, v_num=19, train_loss_step=57.80, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.52it/s, v_num=19, train_loss_step=146.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.52it/s, v_num=19, train_loss_step=146.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.52it/s, v_num=19, train_loss_step=95.60, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=95.60, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.53it/s, v_num=19, train_loss_step=79.60, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=79.60, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.52it/s, v_num=19, train_loss_step=74.70, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.52it/s, v_num=19, train_loss_step=74.70, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.51it/s, v_num=19, train_loss_step=40.10, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.60it/s, v_num=19, train_loss_step=40.10, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.58it/s, v_num=19, train_loss_step=63.50, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=63.50, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.55it/s, v_num=19, train_loss_step=122.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.42it/s, v_num=19, train_loss_step=122.0, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.42it/s, v_num=19, train_loss_step=86.90, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.41it/s, v_num=19, train_loss_step=86.90, val_loss=982.0, train_loss_epoch=86.50]

Epoch 24: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.40it/s, v_num=19, train_loss_step=135.0, val_loss=982.0, train_loss_epoch=86.50]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 45.91it/s]

Epoch 24: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.09it/s, v_num=19, train_loss_step=135.0, val_loss=964.0, train_loss_epoch=86.50]

Epoch 24: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.06it/s, v_num=19, train_loss_step=135.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 24:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=135.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=135.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:   6%|██                                  | 1/18 [00:00<00:01, 10.80it/s, v_num=19, train_loss_step=135.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:   6%|██                                  | 1/18 [00:00<00:01, 10.80it/s, v_num=19, train_loss_step=62.30, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  11%|████                                | 2/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=62.30, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  11%|████                                | 2/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=83.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  17%|██████                              | 3/18 [00:00<00:01, 11.24it/s, v_num=19, train_loss_step=83.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  17%|██████                              | 3/18 [00:00<00:01, 10.62it/s, v_num=19, train_loss_step=75.50, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  22%|████████                            | 4/18 [00:00<00:01, 11.00it/s, v_num=19, train_loss_step=75.50, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  22%|████████                            | 4/18 [00:00<00:01, 11.00it/s, v_num=19, train_loss_step=64.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  28%|██████████                          | 5/18 [00:00<00:01, 10.95it/s, v_num=19, train_loss_step=64.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  28%|██████████                          | 5/18 [00:00<00:01, 10.95it/s, v_num=19, train_loss_step=102.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  33%|████████████                        | 6/18 [00:00<00:01, 10.72it/s, v_num=19, train_loss_step=102.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  33%|████████████                        | 6/18 [00:00<00:01, 10.69it/s, v_num=19, train_loss_step=86.70, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  39%|██████████████                      | 7/18 [00:00<00:01, 10.84it/s, v_num=19, train_loss_step=86.70, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  39%|██████████████                      | 7/18 [00:00<00:01, 10.84it/s, v_num=19, train_loss_step=75.40, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  44%|████████████████                    | 8/18 [00:00<00:00, 10.75it/s, v_num=19, train_loss_step=75.40, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  44%|████████████████                    | 8/18 [00:00<00:00, 10.75it/s, v_num=19, train_loss_step=158.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.64it/s, v_num=19, train_loss_step=158.0, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.64it/s, v_num=19, train_loss_step=75.30, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.77it/s, v_num=19, train_loss_step=75.30, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.77it/s, v_num=19, train_loss_step=96.20, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.68it/s, v_num=19, train_loss_step=96.20, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.68it/s, v_num=19, train_loss_step=86.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.74it/s, v_num=19, train_loss_step=86.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.74it/s, v_num=19, train_loss_step=77.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.83it/s, v_num=19, train_loss_step=77.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.83it/s, v_num=19, train_loss_step=98.70, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.84it/s, v_num=19, train_loss_step=98.70, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.84it/s, v_num=19, train_loss_step=92.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.70it/s, v_num=19, train_loss_step=92.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.70it/s, v_num=19, train_loss_step=72.80, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.80it/s, v_num=19, train_loss_step=72.80, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.80it/s, v_num=19, train_loss_step=97.90, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.80it/s, v_num=19, train_loss_step=97.90, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.79it/s, v_num=19, train_loss_step=82.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.78it/s, v_num=19, train_loss_step=82.60, val_loss=964.0, train_loss_epoch=89.20]

Epoch 25: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.78it/s, v_num=19, train_loss_step=120.0, val_loss=964.0, train_loss_epoch=89.20]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.81it/s]

Epoch 25: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.45it/s, v_num=19, train_loss_step=120.0, val_loss=966.0, train_loss_epoch=89.20]

Epoch 25: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.45it/s, v_num=19, train_loss_step=120.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 25:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=120.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=120.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:   6%|██                                  | 1/18 [00:00<00:01, 11.21it/s, v_num=19, train_loss_step=120.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:   6%|██                                  | 1/18 [00:00<00:01, 11.21it/s, v_num=19, train_loss_step=80.80, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  11%|████                                | 2/18 [00:00<00:01, 10.36it/s, v_num=19, train_loss_step=80.80, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  11%|████                                | 2/18 [00:00<00:01, 10.36it/s, v_num=19, train_loss_step=68.90, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  17%|██████                              | 3/18 [00:00<00:01, 10.14it/s, v_num=19, train_loss_step=68.90, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  17%|██████                              | 3/18 [00:00<00:01, 10.07it/s, v_num=19, train_loss_step=121.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  22%|████████                            | 4/18 [00:00<00:01, 10.32it/s, v_num=19, train_loss_step=121.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  22%|████████                            | 4/18 [00:00<00:01, 10.32it/s, v_num=19, train_loss_step=83.80, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  28%|██████████                          | 5/18 [00:00<00:01, 10.26it/s, v_num=19, train_loss_step=83.80, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  28%|██████████                          | 5/18 [00:00<00:01, 10.22it/s, v_num=19, train_loss_step=159.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  33%|████████████                        | 6/18 [00:00<00:01, 10.11it/s, v_num=19, train_loss_step=159.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  33%|████████████                        | 6/18 [00:00<00:01, 10.07it/s, v_num=19, train_loss_step=103.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  39%|██████████████                      | 7/18 [00:00<00:01, 10.19it/s, v_num=19, train_loss_step=103.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  39%|██████████████                      | 7/18 [00:00<00:01, 10.16it/s, v_num=19, train_loss_step=40.70, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  44%|████████████████                    | 8/18 [00:00<00:00, 10.22it/s, v_num=19, train_loss_step=40.70, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  44%|████████████████                    | 8/18 [00:00<00:00, 10.22it/s, v_num=19, train_loss_step=93.10, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.24it/s, v_num=19, train_loss_step=93.10, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.22it/s, v_num=19, train_loss_step=84.30, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.05it/s, v_num=19, train_loss_step=84.30, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.03it/s, v_num=19, train_loss_step=109.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.16it/s, v_num=19, train_loss_step=109.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.14it/s, v_num=19, train_loss_step=115.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=115.0, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=86.70, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.24it/s, v_num=19, train_loss_step=86.70, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.24it/s, v_num=19, train_loss_step=75.00, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.16it/s, v_num=19, train_loss_step=75.00, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=60.20, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.18it/s, v_num=19, train_loss_step=60.20, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.16it/s, v_num=19, train_loss_step=72.00, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.12it/s, v_num=19, train_loss_step=72.00, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.12it/s, v_num=19, train_loss_step=91.00, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.17it/s, v_num=19, train_loss_step=91.00, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.15it/s, v_num=19, train_loss_step=66.20, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.20it/s, v_num=19, train_loss_step=66.20, val_loss=966.0, train_loss_epoch=89.40]

Epoch 26: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.19it/s, v_num=19, train_loss_step=63.80, val_loss=966.0, train_loss_epoch=89.40]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.59it/s]

Epoch 26: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=63.80, val_loss=962.0, train_loss_epoch=89.40]

Epoch 26: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.88it/s, v_num=19, train_loss_step=63.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 26:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=63.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=63.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:   6%|██                                  | 1/18 [00:00<00:01, 12.65it/s, v_num=19, train_loss_step=63.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:   6%|██                                  | 1/18 [00:00<00:01, 12.65it/s, v_num=19, train_loss_step=69.70, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  11%|████                                | 2/18 [00:00<00:01, 11.50it/s, v_num=19, train_loss_step=69.70, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  11%|████                                | 2/18 [00:00<00:01, 11.50it/s, v_num=19, train_loss_step=100.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  17%|██████                              | 3/18 [00:00<00:01, 10.91it/s, v_num=19, train_loss_step=100.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  17%|██████                              | 3/18 [00:00<00:01, 10.91it/s, v_num=19, train_loss_step=125.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  22%|████████                            | 4/18 [00:00<00:01, 11.00it/s, v_num=19, train_loss_step=125.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  22%|████████                            | 4/18 [00:00<00:01, 11.00it/s, v_num=19, train_loss_step=144.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  28%|██████████                          | 5/18 [00:00<00:01, 10.74it/s, v_num=19, train_loss_step=144.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  28%|██████████                          | 5/18 [00:00<00:01, 10.74it/s, v_num=19, train_loss_step=62.30, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  33%|████████████                        | 6/18 [00:00<00:01, 10.26it/s, v_num=19, train_loss_step=62.30, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  33%|████████████                        | 6/18 [00:00<00:01, 10.26it/s, v_num=19, train_loss_step=86.50, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  39%|██████████████                      | 7/18 [00:00<00:01, 10.30it/s, v_num=19, train_loss_step=86.50, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  39%|██████████████                      | 7/18 [00:00<00:01, 10.30it/s, v_num=19, train_loss_step=59.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  44%|████████████████                    | 8/18 [00:00<00:01,  9.93it/s, v_num=19, train_loss_step=59.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  44%|████████████████                    | 8/18 [00:00<00:01,  9.93it/s, v_num=19, train_loss_step=112.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  50%|██████████████████                  | 9/18 [00:00<00:00,  9.78it/s, v_num=19, train_loss_step=112.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  50%|██████████████████                  | 9/18 [00:00<00:00,  9.78it/s, v_num=19, train_loss_step=66.40, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.88it/s, v_num=19, train_loss_step=66.40, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  56%|███████████████████▍               | 10/18 [00:01<00:00,  9.88it/s, v_num=19, train_loss_step=74.50, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.85it/s, v_num=19, train_loss_step=74.50, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  61%|█████████████████████▍             | 11/18 [00:01<00:00,  9.84it/s, v_num=19, train_loss_step=63.30, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  67%|███████████████████████▎           | 12/18 [00:01<00:00,  9.88it/s, v_num=19, train_loss_step=63.30, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  67%|███████████████████████▎           | 12/18 [00:01<00:00,  9.88it/s, v_num=19, train_loss_step=47.20, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  72%|█████████████████████████▎         | 13/18 [00:01<00:00,  9.89it/s, v_num=19, train_loss_step=47.20, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  72%|█████████████████████████▎         | 13/18 [00:01<00:00,  9.89it/s, v_num=19, train_loss_step=103.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  78%|███████████████████████████▏       | 14/18 [00:01<00:00,  9.87it/s, v_num=19, train_loss_step=103.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  78%|███████████████████████████▏       | 14/18 [00:01<00:00,  9.85it/s, v_num=19, train_loss_step=69.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=69.80, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00,  9.90it/s, v_num=19, train_loss_step=126.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  89%|███████████████████████████████    | 16/18 [00:01<00:00,  9.93it/s, v_num=19, train_loss_step=126.0, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  89%|███████████████████████████████    | 16/18 [00:01<00:00,  9.93it/s, v_num=19, train_loss_step=65.10, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  94%|█████████████████████████████████  | 17/18 [00:01<00:00,  9.96it/s, v_num=19, train_loss_step=65.10, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27:  94%|█████████████████████████████████  | 17/18 [00:01<00:00,  9.96it/s, v_num=19, train_loss_step=56.40, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.96it/s, v_num=19, train_loss_step=56.40, val_loss=962.0, train_loss_epoch=87.40]

Epoch 27: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.96it/s, v_num=19, train_loss_step=72.10, val_loss=962.0, train_loss_epoch=87.40]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 46.07it/s]

Epoch 27: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.71it/s, v_num=19, train_loss_step=72.10, val_loss=973.0, train_loss_epoch=87.40]

Epoch 27: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.66it/s, v_num=19, train_loss_step=72.10, val_loss=973.0, train_loss_epoch=83.50]

Epoch 27:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=72.10, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=72.10, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:   6%|██                                  | 1/18 [00:00<00:01, 10.48it/s, v_num=19, train_loss_step=72.10, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:   6%|██                                  | 1/18 [00:00<00:01,  8.99it/s, v_num=19, train_loss_step=69.60, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  11%|████                                | 2/18 [00:00<00:01, 10.17it/s, v_num=19, train_loss_step=69.60, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  11%|████                                | 2/18 [00:00<00:01, 10.17it/s, v_num=19, train_loss_step=82.30, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  17%|██████                              | 3/18 [00:00<00:01, 10.51it/s, v_num=19, train_loss_step=82.30, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  17%|██████                              | 3/18 [00:00<00:01, 10.51it/s, v_num=19, train_loss_step=65.20, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  22%|████████                            | 4/18 [00:00<00:01,  9.98it/s, v_num=19, train_loss_step=65.20, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  22%|████████                            | 4/18 [00:00<00:01,  9.94it/s, v_num=19, train_loss_step=87.40, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  28%|██████████                          | 5/18 [00:00<00:01, 10.19it/s, v_num=19, train_loss_step=87.40, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  28%|██████████                          | 5/18 [00:00<00:01, 10.19it/s, v_num=19, train_loss_step=107.0, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  33%|████████████                        | 6/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=107.0, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  33%|████████████                        | 6/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=72.30, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  39%|██████████████                      | 7/18 [00:00<00:01, 10.53it/s, v_num=19, train_loss_step=72.30, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  39%|██████████████                      | 7/18 [00:00<00:01, 10.53it/s, v_num=19, train_loss_step=70.90, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  44%|████████████████                    | 8/18 [00:00<00:00, 10.52it/s, v_num=19, train_loss_step=70.90, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  44%|████████████████                    | 8/18 [00:00<00:00, 10.31it/s, v_num=19, train_loss_step=95.90, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.30it/s, v_num=19, train_loss_step=95.90, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.27it/s, v_num=19, train_loss_step=89.60, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.36it/s, v_num=19, train_loss_step=89.60, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.36it/s, v_num=19, train_loss_step=84.20, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=84.20, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=76.40, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.29it/s, v_num=19, train_loss_step=76.40, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.27it/s, v_num=19, train_loss_step=65.80, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.28it/s, v_num=19, train_loss_step=65.80, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.28it/s, v_num=19, train_loss_step=42.30, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.30it/s, v_num=19, train_loss_step=42.30, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.29it/s, v_num=19, train_loss_step=79.00, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.35it/s, v_num=19, train_loss_step=79.00, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=133.0, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.44it/s, v_num=19, train_loss_step=133.0, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.34it/s, v_num=19, train_loss_step=34.60, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.42it/s, v_num=19, train_loss_step=34.60, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.41it/s, v_num=19, train_loss_step=119.0, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.39it/s, v_num=19, train_loss_step=119.0, val_loss=973.0, train_loss_epoch=83.50]

Epoch 28: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.39it/s, v_num=19, train_loss_step=64.70, val_loss=973.0, train_loss_epoch=83.50]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.66it/s]

Epoch 28: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.08it/s, v_num=19, train_loss_step=64.70, val_loss=944.0, train_loss_epoch=83.50]

Epoch 28: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.06it/s, v_num=19, train_loss_step=64.70, val_loss=944.0, train_loss_epoch=80.00]

Epoch 28:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=64.70, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:   0%|                                            | 0/18 [00:00<?, ?it/s, v_num=19, train_loss_step=64.70, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:   6%|██                                  | 1/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=64.70, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:   6%|██                                  | 1/18 [00:00<00:01, 10.38it/s, v_num=19, train_loss_step=39.00, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  11%|████                                | 2/18 [00:00<00:01, 10.36it/s, v_num=19, train_loss_step=39.00, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  11%|████                                | 2/18 [00:00<00:01, 10.25it/s, v_num=19, train_loss_step=111.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  17%|██████                              | 3/18 [00:00<00:01, 10.65it/s, v_num=19, train_loss_step=111.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  17%|██████                              | 3/18 [00:00<00:01, 10.57it/s, v_num=19, train_loss_step=51.50, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  22%|████████                            | 4/18 [00:00<00:01, 10.57it/s, v_num=19, train_loss_step=51.50, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  22%|████████                            | 4/18 [00:00<00:01, 10.57it/s, v_num=19, train_loss_step=110.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  28%|██████████                          | 5/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=110.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  28%|██████████                          | 5/18 [00:00<00:01, 10.55it/s, v_num=19, train_loss_step=57.60, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  33%|████████████                        | 6/18 [00:00<00:01, 10.41it/s, v_num=19, train_loss_step=57.60, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  33%|████████████                        | 6/18 [00:00<00:01, 10.41it/s, v_num=19, train_loss_step=55.20, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  39%|██████████████                      | 7/18 [00:00<00:01, 10.49it/s, v_num=19, train_loss_step=55.20, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  39%|██████████████                      | 7/18 [00:00<00:01, 10.49it/s, v_num=19, train_loss_step=76.70, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  44%|████████████████                    | 8/18 [00:00<00:00, 10.38it/s, v_num=19, train_loss_step=76.70, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  44%|████████████████                    | 8/18 [00:00<00:00, 10.38it/s, v_num=19, train_loss_step=137.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.55it/s, v_num=19, train_loss_step=137.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  50%|██████████████████                  | 9/18 [00:00<00:00, 10.55it/s, v_num=19, train_loss_step=97.10, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.37it/s, v_num=19, train_loss_step=97.10, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  56%|███████████████████▍               | 10/18 [00:00<00:00, 10.37it/s, v_num=19, train_loss_step=76.20, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.35it/s, v_num=19, train_loss_step=76.20, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  61%|█████████████████████▍             | 11/18 [00:01<00:00, 10.33it/s, v_num=19, train_loss_step=129.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.21it/s, v_num=19, train_loss_step=129.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  67%|███████████████████████▎           | 12/18 [00:01<00:00, 10.21it/s, v_num=19, train_loss_step=54.80, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.22it/s, v_num=19, train_loss_step=54.80, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  72%|█████████████████████████▎         | 13/18 [00:01<00:00, 10.22it/s, v_num=19, train_loss_step=137.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.30it/s, v_num=19, train_loss_step=137.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  78%|███████████████████████████▏       | 14/18 [00:01<00:00, 10.30it/s, v_num=19, train_loss_step=74.20, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.21it/s, v_num=19, train_loss_step=74.20, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  83%|█████████████████████████████▏     | 15/18 [00:01<00:00, 10.21it/s, v_num=19, train_loss_step=113.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.12it/s, v_num=19, train_loss_step=113.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  89%|███████████████████████████████    | 16/18 [00:01<00:00, 10.12it/s, v_num=19, train_loss_step=79.10, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.11it/s, v_num=19, train_loss_step=79.10, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29:  94%|█████████████████████████████████  | 17/18 [00:01<00:00, 10.11it/s, v_num=19, train_loss_step=106.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.17it/s, v_num=19, train_loss_step=106.0, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29: 100%|███████████████████████████████████| 18/18 [00:01<00:00, 10.17it/s, v_num=19, train_loss_step=97.90, val_loss=944.0, train_loss_epoch=80.00]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation: |                                                                                                                        | 0/? [00:00<?, ?it/s]

Validation DataLoader 0:   0%|                                                                                                       | 0/1 [00:00<?, ?it/s]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.43it/s]

Epoch 29: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.81it/s, v_num=19, train_loss_step=97.90, val_loss=944.0, train_loss_epoch=80.00]

Epoch 29: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.81it/s, v_num=19, train_loss_step=97.90, val_loss=944.0, train_loss_epoch=89.10]

`Trainer.fit` stopped: `max_epochs=30` reached.

Epoch 29: 100%|███████████████████████████████████| 18/18 [00:01<00:00,  9.25it/s, v_num=19, train_loss_step=97.90, val_loss=944.0, train_loss_epoch=89.10]

In [8]:
import torch
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

prediction = tft.predict(valid_loader, mode="prediction", return_x=True)

pred = prediction.output.cpu().numpy().reshape(-1)
y_true = prediction.x["decoder_target"].cpu().numpy().reshape(-1)

rmse = np.sqrt(mean_squared_error(y_true, pred))
mae  = mean_absolute_error(y_true, pred)

# Tính MAPE (xử lý mẫu số = 0)
denom = np.where(y_true == 0, 1, y_true)
mape = np.mean(np.abs((y_true - pred) / denom))

tft_metrics = {"rmse": rmse, "mae": mae, "mape": mape}
print(tft_metrics)

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: False, used: False

TPU available: False, using: 0 TPU cores

{'rmse': np.float64(4696.698840675224), 'mae': 1069.449462890625, 'mape': np.float32(2.3584862)}

In [9]:
arima_df   = pd.DataFrame(arima_metrics).assign(model="ARIMA")
prophet_df = pd.DataFrame(prophet_metrics).assign(model="Prophet")
tft_df     = pd.DataFrame([tft_metrics]).assign(model="TFT", group_id="ALL_TOP10")

metrics_all = pd.concat([arima_df, prophet_df, tft_df], ignore_index=True)
metrics_all.to_csv(r"D:\STAT3013.Q12_Group01\results\forecast_metrics.csv", index=False)

metrics_all

      group_id          rmse           mae      mape    model
0      GROCERY   5438.531607   5435.013845  0.125639    ARIMA
1      GROCERY   3832.218454   3008.033257  0.061956    ARIMA
2      GROCERY   6031.607976   6031.580351  0.139337    ARIMA
3      GROCERY   5532.119299   4659.458096  0.094531    ARIMA
4      GROCERY  33568.388314  26786.321863  3.987424    ARIMA
..         ...           ...           ...       ...      ...
96   NUTRITION     75.789295     72.720798  0.068884  Prophet
97   NUTRITION     72.709599     71.735986  0.063129  Prophet
98   NUTRITION    169.324904    169.285981  0.163305  Prophet
99   NUTRITION    782.063576    647.734319  3.929288  Prophet
100  ALL_TOP10   4696.698841   1069.449463  2.358486      TFT

[101 rows x 5 columns]

In [10]:
# ===== NB06: SAVE RESULTS =====
import pandas as pd
import numpy as np

# Dùng RESULTS đọc từ config (đã khai báo ở Cell 0)
OUT_DIR = RESULTS
OUT_DIR.mkdir(exist_ok=True)

# 1) ARIMA / Prophet metrics DF
arima_df   = pd.DataFrame(arima_metrics).assign(model="ARIMA")
prophet_df = pd.DataFrame(prophet_metrics).assign(model="Prophet")

# 2) TFT metrics DF (overall top10)
tft_df = pd.DataFrame([tft_metrics]).assign(model="TFT", group_id="ALL_TOP10")

# 3) Save combined forecasting metrics
metrics_all = pd.concat([arima_df, prophet_df, tft_df], ignore_index=True)
metrics_path = OUT_DIR / "forecast_metrics.csv"
metrics_all.to_csv(metrics_path, index=False)
print("Saved forecast_metrics.csv to:", metrics_path)

# 4) Save riêng TFT metrics (để report dễ trích)
tft_metrics_path = OUT_DIR / "nb06_tft_metrics.csv"
tft_df.to_csv(tft_metrics_path, index=False)
print("Saved nb06_tft_metrics.csv to:", tft_metrics_path)

# 5) Save raw TFT predictions vs actual
tft_pred_df = pd.DataFrame({"y_true": y_true, "y_pred": pred})
tft_pred_path = OUT_DIR / "nb06_tft_preds.parquet"
tft_pred_df.to_parquet(tft_pred_path, index=False)
print("Saved nb06_tft_preds.parquet to:", tft_pred_path)

metrics_all.head()

Saved forecast_metrics.csv to: D:\STAT3013.Q12_Group01\results\forecast_metrics.csv
Saved nb06_tft_metrics.csv to: D:\STAT3013.Q12_Group01\results\nb06_tft_metrics.csv
Saved nb06_tft_preds.parquet to: D:\STAT3013.Q12_Group01\results\nb06_tft_preds.parquet

  group_id          rmse           mae      mape  model
0  GROCERY   5438.531607   5435.013845  0.125639  ARIMA
1  GROCERY   3832.218454   3008.033257  0.061956  ARIMA
2  GROCERY   6031.607976   6031.580351  0.139337  ARIMA
3  GROCERY   5532.119299   4659.458096  0.094531  ARIMA
4  GROCERY  33568.388314  26786.321863  3.987424  ARIMA